### ISSUE TITLE
dnndk with Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104 2021.1

### ISSUE THREAD

**Issue by arrow53** [Xilinx/Vitis-Tutorials#107]
with the 2021.1 release, during step 2 `petalinux-build` fails on building several packages. I can get around a lot of them by including the vitisai meta layer via the instructions at the end of this

https://forums.xilinx.com/t5/Embedded-Linux/Petalinux-2021-1-packagegroup-petalinux-vitisai-problem/m-p/1280715/highlight/true#M52489

But, I think this still doesn't include dnndk? Is there a way to add it?

**Comment by imrickysu** [comment]
I don't think DNNDK is supported in this release. I'll confirm with Vitis-AI team.

**Comment by shua1zhang** [comment]
Hi @arrow53 ,
The VAI 1.4 will not have DNNDK.
