### ISSUE TITLE
Embedded Design Tutorials/Zynq UltraScale+ MPSoC Embedded Design Tutorial/Design Example 1: Using GPIOs, Timers, and Interrupts/  can't open The "ref_design"  example  URL

### ISSUE THREAD

**Issue by LoeWHJ** [Xilinx/Vitis-Tutorials#112]

**Comment by imrickysu** [comment]
Hi @LoeWHJ , could you share more details in your question?

Do you mean this folder? 
https://github.com/Xilinx/Embedded-Design-Tutorials/tree/master/docs/Introduction/ZynqMPSoC-EDT/ref_files

Embedded Design Tutorials is a github repo outside of Vitis-Tutorials.

**Comment by ryanvergel** [comment]
Closing this issue and opening an issue in [https://github.com/Xilinx/Embedded-Design-Tutorials/](https://github.com/Xilinx/Embedded-Design-Tutorials/tree/master/docs/Introduction/ZynqMPSoC-EDT/ref_files)
