### ISSUE TITLE
File not found common/xf_common.hpp when building Runtime_and_System_Optimization/Introduction/design_source/hw_src

### ISSUE THREAD

**Issue by CoffeeCat3008871** [Xilinx/Vitis-Tutorials#120]
After I downloaded the package throught "git clone --recurse-submodules https://github.com/Xilinx/Vitis-Tutorials.git", I followed the instruction to go into the hw_src file and change the first line of Makefile. I setup the Vitis and XRT environment through "source /opt/Xilinx/Vivado/2021.1/settings64.sh" and "source /opt/xilinx/xrt/setup.sh" correctly. However, when I did "make", the result looked as the followings:

INFO: [v++ 60-242] Creating kernel: 'resize_accel_rgb'

===>The following messages were generated while  performing high-level synthesis for kernel: resize_accel_rgb Log file: /home/moore/git/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log :
ERROR: [v++ 207-812] 'common/xf_common.hpp' file not found: /home/moore/git/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/resize_rgb.cpp:32:10
ERROR: [v++ 60-300] Failed to build kernel(ip) resize_accel_rgb, see log for details: /home/moore/git/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log
ERROR: [v++ 60-773] In '/home/moore/git/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log', caught Tcl error: ERROR: [HLS 207-812] 'common/xf_common.hpp' file not found: /home/moore/git/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/resize_rgb.cpp:32:10
ERROR: [v++ 60-599] Kernel compilation failed to complete
ERROR: [v++ 60-592] Failed to finish compilation
INFO: [v++ 60-1653] Closing dispatch client.
Makefile:40: recipe for target 'resize_rgb.xo' failed
make: *** [resize_rgb.xo] Error 1

**Comment by arrow53** [comment]
@CrunchyMoore this is fixed on the 2021.2 branch.

**Comment by Premduth** [comment]
Closing based on last comment from @arrow53

**Comment by winnieaswin** [comment]
Hi, I am on 2021.2 and I've got the same problem. 

INFO: [v++ 60-1316] Initiating connection to rulecheck server, at Sun May 29 21:45:42 2022
INFO: [v++ 60-1315] Creating rulecheck session with output '/home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/reports/resize_rgb/v++_compile_resize_rgb_guidance.html', at Sun May 29 21:45:43 2022
INFO: [v++ 60-895]   Target platform: /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/xilinx_u50_gen3x16_xdma_201920_3.xpfm
INFO: [v++ 60-1578]   This platform contains Xilinx Shell Archive '/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_201920_3/hw/hw.xsa'
INFO: [v++ 74-78] Compiler Version string: 2021.2
INFO: [v++ 60-1302] Platform 'xilinx_u50_gen3x16_xdma_201920_3.xpfm' has been explicitly enabled for this release.
INFO: [v++ 60-585] Compiling for hardware target
INFO: [v++ 60-423]   Target device: xilinx_u50_gen3x16_xdma_201920_3
INFO: [v++ 60-242] Creating kernel: 'resize_accel_rgb'

===>The following messages were generated while  performing high-level synthesis for kernel: resize_accel_rgb Log file: /home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log :
ERROR: [v++ 207-812] 'common/xf_common.hpp' file not found (/home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/resize_rgb.cpp:32:10)
ERROR: [v++ 60-300] Failed to build kernel(ip) resize_accel_rgb, see log for details: /home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log
ERROR: [v++ 60-773] In '/home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log', caught Tcl error: ERROR: [HLS 207-812] 'common/xf_common.hpp' file not found (/home/win/vantaCapital/Tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/resize_rgb.cpp:32:10)
ERROR: [v++ 60-599] Kernel compilation failed to complete
ERROR: [v++ 60-592] Failed to finish compilation
INFO: [v++ 60-1653] Closing dispatch client.
make: *** [Makefile:40: resize_rgb.xo] Error 1

**Comment by winnieaswin** [comment]
To solve the problem I copy all folder Vitis_Libraries into /design_source/hw_src
