### ISSUE TITLE
Pre-synthesis Control Flow Error occurred after running C simulation

### ISSUE THREAD

**Issue by CoffeeCat3008871** [Xilinx/Vitis-Tutorials#121]
After I ran the C simulation on the synthesis and analysis part of the Vitis HLS Getting Started tutorial, the dct_csim.log gave TEST PASSED, but the Pre-synthesis control flow did not show up and an error occurred in the problem console as the followings:

![Error_1](https://user-images.githubusercontent.com/89786846/139447075-5080867e-2adc-4916-927e-c2c6e28daa07.PNG)
![Error_2](https://user-images.githubusercontent.com/89786846/139447085-c937e556-421b-4934-a505-2ce3f84b84db.PNG)

**Comment by danna2019** [comment]
Same problem reported on [Xilinx forum](https://support.xilinx.com/s/question/0D52E00006hpP0FSAU/failed-to-create-the-parts-controls-error-when-running-vitis-hls-tutorials), but not solved.

**Comment by randyh62** [comment]
Can you post your operating system information here?

**Comment by CoffeeCat3008871** [comment]
![image](https://user-images.githubusercontent.com/89786846/139568050-af4b617b-5627-4dd8-9b2c-d1f30dd23f54.png)

**Comment by lefmylonas** [comment]
Hi all,

Is there any update regarding this issue? I am having the same problem in Vitis HLS 2020.2 on Ubuntu 20.04.6 LTS.

**Comment by randyh62** [comment]
The issue appears to be something related to the environment or system setup. I was not able to recreate the problem described above. Can you share any additional information related to your environment?

**Comment by lefmylonas** [comment]
Hi again and thank you for the quick reply!

Actually i found the problem in my case. There was a problem with my setup. I had to change my default desktop environment with this command "$ sudo update-alternatives --config x-session-manager".
