### ISSUE TITLE
Example of a project for Vitis HLS, Vitis Vision Library

### ISSUE THREAD

**Issue by drug490** [Xilinx/Vitis-Tutorials#134]
Hello, I need an example of a project for Vitis HLS, Vitis Vision Library, to create an IP block that works with AXI Video Stream. Like this

https://www.hackster.io/adam-taylor/fpga-based-edge-detection-using-hls-192ad2

##include "hlc_video.h"

#include "hls_OpenCV.h"

Does not work in Vitis HLS 2021.1

**Comment by allyzhou** [comment]
The vitis vision librares are deprecated in vitis HLS, which is documented in here -https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/HLS-Video-Library 


The new Vitis Vision libraries can be found in here - https://xilinx.github.io/Vitis_Libraries/vision/2021.2/overview.html# . 
The vitis Stream example can be found in here -  https://github.com/Xilinx/Vitis-HLS-Introductory-Examples/tree/master/Interface/Streaming/using_axi_stream_with_side_channel_data
