### ISSUE TITLE
In the Thin Platform it shows how to use ILA with AIE Debug, although the Readme does not call this out

### ISSUE THREAD

**Issue by Premduth** [Xilinx/Vitis-Tutorials#136]
The Readme for the Thin platform does not clarify that AIE Debug of the system is included in the tutorial. Can that be added please?

**Comment by BrunoVandeveldeXilinx** [comment]
More info on AIE ILA/Debug has been added to the README.md and will be available on the next upload to github.
Kudos to Marco!

**Comment by Premduth** [comment]
@BrunoVandeveldeXilinx can you submit a PR to Github for this change? then we can link this with the issue request..

**Comment by BrunoVandeveldeXilinx** [comment]
@Premduth We have done a pull request to the internal gitenterprise, so I assume it will come to life next week Friday! Or if you like it sooner on github than @allyzhou needs to accept the PR sooner.

**Comment by allyzhou** [comment]
issue fixed by commit b2890fcef3a6669ddfdc06458a7eea0e589e627c
