### ISSUE TITLE
unable Export Hardware XSA as Vitis Custom Embedded Platform Creation Example on KV260

### ISSUE THREAD

**Issue by dongzhang2021** [Xilinx/Vitis-Tutorials#140]
```
INFO: [Project 1-1042] Successfully generated hpfm file
unmatched open brace in  #list
ERROR: [Common 17-69] Command failed: unmatched open brace in list
```
vado2021.1
Vi
![2021-12-09 02-13-38屏幕截图](https://user-images.githubusercontent.com/90568145/145261716-6c9fd6a1-b3dd-404b-a6ed-3422d584b59c.png)
![xsa_axi](https://user-images.githubusercontent.com/90568145/145261589-2afae171-2282-4680-bc56-593bae575dd3.png)
![xsa_clk](https://user-images.githubusercontent.com/90568145/145261605-8a40f119-0ddc-46b4-aa2a-a61a51660dab.png)
![xsa_inter](https://user-images.githubusercontent.com/90568145/145261615-7069b616-b649-4556-b0d3-75a1508b1ecd.png)

**Comment by imrickysu** [comment]
Hi @dongzhang2021 , could you attach the logs in Vivado console? I wish to check the Tcl command for export and the full error message. Thanks.

**Comment by dongzhang2021** [comment]
hi  @imrickysu  ,Is this part of the information?Thank you for your help

1. `start_gui
2. open_project /media/tnt/Workspace/Xilinx/kv260_202101/zc104_202101.xpr
3. open_project /media/tnt/Workspace/Xilinx/kv260_202101/zc104_202101.xpr
4. INFO: [Project 1-313] Project file moved from '/media/tnt/Workspace/Xilinx/zc104_202101' since last save.
5. Scanning sources...
6. Finished scanning sources
7. INFO: [IP_Flow 19-234] Refreshing IP repositories
8. INFO: [IP_Flow 19-1704] No user IP repositories specified
9. INFO: [IP_Flow 19-2313] Loaded Vivado IP repository '/tools/Xilinx/Vivado/2021.1/data/ip'.
10. INFO: [IP_Flow 19-3899] Cannot get the environment domain name variable for the component vendor name. Setting the vendor name to 'user.org'.
11. open_project: Time (s): cpu = 00:00:15 ; elapsed = 00:00:05 . Memory (MB): peak = 7548.859 ; gain = 71.301 ; free physical = 49878 ; free virtual = 57760
12. update_compile_order -fileset sources_1
13. set_property pfm_name {xilinx:kv260:nam:0.0} [get_files -all {/media/tnt/Workspace/Xilinx/kv260_202101/zc104_202101.srcs/sources_1/bd/kv260_pl/kv260_pl.bd}]
14. set_property platform.uses_pr {false} [current_project]
15. write_hw_platform -hw -force -file /media/tnt/Workspace/Xilinx/kv260_202101/kv260_pl_wrapper.xsa
16. INFO: [Vivado 12-4895] Creating Hardware Platform: /media/tnt/Workspace/Xilinx/kv260_202101/kv260_pl_wrapper.xsa ...
17. INFO: [Hsi 55-2053] elapsed time for repository (/tools/Xilinx/Vivado/2021.1/data/embeddedsw) loading 0 seconds
18. WARNING: [BD 41-2589] Platform should have atleast one axi memory mapped master interface. Enable a master AXI interface as platform AXI_PORT.
19. INFO: [Project 1-1042] Successfully generated hpfm file
20. unmatched open brace in list
21. ERROR: [Common 17-69] Command failed: unmatched open brace in list`

**Comment by dongzhang2021** [comment]
``

**Comment by dongzhang2021** [comment]
@imrickysu Sorry, I closed the question by mistake

**Comment by IvoBrandao** [comment]
I have the same behavior in 2021.2 version
Is there a fix for this issue?

**Comment by imrickysu** [comment]
Hi @IvoBrandao , Dongzhang created another thread in https://github.com/Xilinx/Vitis-Tutorials/issues/144 but didn't add more reply. May I know which OS you're running? Is it Windows or Linux? Is there any modifications you made based on the reference files?

**Comment by IvoBrandao** [comment]
@imrickysu I'm running Ubuntu 20.04. I tried to create the platform from scratch, so I might have made some mistakes. I just started the Vivado project again and this time everything worked, as the tutorials mention. The weird thing is that I follow the same steps. So not sure why this problem appears. Anyway, thanks for following up on the question :+1:

**Comment by AnusheelXilinx** [comment]
Recent issue was addressed in its respective thread. Closing this thread as there are no open concerns.

Thanks
Anusheel
