### ISSUE TITLE
On (2021.2) Vitis-Tutorials/Hardware_Acceleration/Introduction, Hardware Emulation doesn't work

### ISSUE THREAD

**Issue by xooxit** [Xilinx/Vitis-Tutorials#141]
Hi- I'm trying to reproduce Hardware_Acceleration Introduction in various ways.
So I'm gonna build Hardware Design as hardware emulation mode and 
change _Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/config.mk_ file like below

```
# Options for TARGET: sw_emu, hw_emu and hw
TARGET ?= hw_emu
# Options for DEVICE: u200, u250. Default platform is XDMA, defined by PLATFORM
DEVICE ?= u250
# If other some specific platforms needs to be used, provide platform path directly
PLATFORM ?= xilinx_$(DEVICE)_xdma_201830_2
# If your platform is not in the standard install area edit this line
PLATFORM_REPO_PATH ?= /opt/xilinx/platforms/
```

After changing _config.mk_ file, I follow **Building the Hardware Design** procedure and **Building the Software Design** procedure. 
But I get a XRT error like below. (Though, it works well when TARGET=hw)
```
$ ./00_load_kernels 
-- Example 0: Loading the FPGA Binary --

Loading alveo_examples.xclbin to program the Alveo board

XRT build version: 2.6.655
Build hash: 2d6bfe4ce91051d4e5b499d38fc493586dd4859a
Build date: 2020-05-22 12:05:03
Git branch: 2020.1
PID: 16271
UID: 1001
[Thu Dec 16 11:01:34 2021]
HOST: user
EXE: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/build/00_load_kernels
[XRT] ERROR: See dmesg log for details. err=-22
[XRT] ERROR: Failed to load xclbin.
terminate called after throwing an instance of 'LineException'
  what():  (xilinx_ocl_helper.cpp:72) Provided XCLBIN is not compatible with any system device
   (Invalid argument)

Aborted (core dumped)
```

The dmesg is as followed. (Being bolded means RED printed dmesg.)

> [  741.004555] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 icap_cached_ocl_frequency: no cached data for 3
> [  741.017809] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 icap_cached_ocl_frequency: no cached data for 3
> [  741.040873] xocl 0000:af:00.1: rom.u.0 ffff911ab72a1810 verify_timestamp: Shell timestamp: 0x5d14fbe6
> [  741.040875] xocl 0000:af:00.1: rom.u.0 ffff911ab72a1810 verify_timestamp: Verify timestamp: 0x5d14fbe6
> [  741.054938] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: trying to find section header for axlf section 20
> [  741.054941] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 4
> [  741.054942] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 9
> [  741.054943] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 0
> [  741.054944] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 6
> [  741.054945] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 8
> [  741.054947] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 7
> [  741.054948] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 14
> [  741.054949] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 2
> [  741.054950] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: saw section header: 22
> [  741.054951] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_axlf_section_header: could not find section header 20
> [  741.054953] [drm] Finding MEM_TOPOLOGY section header
> [  741.054953] [drm] Section MEM_TOPOLOGY details:
> [  741.054954] [drm]   offset = 0x17f1528
> [  741.054955] [drm]   size = 0x148
> [  741.054961] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_cleanup_mem: Taking down DDR : 0
> [  741.054974] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_cleanup_mem: Taking down DDR : 1
> [  741.054984] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 get_axlf_section_hdr: could not find section header 20
> [  741.054988] xocl 0000:af:00.1: rom.u.0 ffff911ab72a1810 verify_timestamp: Shell timestamp: 0x5d14fbe6
> [  741.054989] xocl 0000:af:00.1: rom.u.0 ffff911ab72a1810 verify_timestamp: Verify timestamp: 0x5d14fbe6
> [  741.054992] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 __icap_download_bitstream_axlf: incoming xclbin: 50c278a2-318c-4c17-8eeb-b9898d680e18
>                on device xclbin: 8ce40966-a276-4968-ab5c-8f9d09919e86
> [  741.054995] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev cu, cdev 0000000000000000
> [  741.055179] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev trace_s2mm, cdev 00000000ab9f32a3
> [  741.055353] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev trace_funnel, cdev 00000000fb5c295f
> [  741.055442] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev accel_mon, cdev 000000009e76f7fc
> [  741.055516] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev aximm_mon, cdev 000000007039fb09
> [  741.055586] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev aximm_mon, cdev 00000000d0b93658
> [  741.055655] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev aximm_mon, cdev 000000007bb78b81
> [  741.055748] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev mig, cdev 0000000000000000
> [  741.055795] xocl 0000:af:00.1:  ffff912ab9c140b0 __xocl_subdev_destroy: Destroy subdev mig, cdev 0000000000000000
> [  741.055854] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 icap_refresh_addrs: memcalib @ 0
> [  741.055861] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 get_axlf_section_hdr: section 6 offset: 25105704, size: 328
> [  741.055874] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 icap_parse_bitstream_axlf_section: icap_parse_bitstream_axlf_section kind 6, err: 0
> [  741.055885] xocl 0000:af:00.1: mailbox.u.15728640 ffff912aaf543c10 mailbox_request: sending request: 7 via HW
> [  741.056043] xclmgmt 0000:af:00.0: mailbox.m.15728640 ffff912ab0e94410 process_request: received request from peer: 7, passed on
> [  741.069651] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: could not find section header 20
> [  741.069658] xclmgmt 0000:af:00.0: rom.m.0 ffff912ab765d410 verify_timestamp: Shell timestamp: 0x5d14fbe6
> [  741.069660] xclmgmt 0000:af:00.0: rom.m.0 ffff912ab765d410 verify_timestamp: Verify timestamp: 0x5d14fbe6
> [  741.069663] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 __icap_download_bitstream_axlf: incoming xclbin: 50c278a2-318c-4c17-8eeb-b9898d680e18
>                on device xclbin: 8ce40966-a276-4968-ab5c-8f9d09919e86
> [  741.069667] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 raptor_cmc_access: No ep_cmc_mutex_00 resource, skip.
> [  741.069697] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 __xocl_subdev_destroy: Destroy subdev mig, cdev 0000000000000000
> [  741.069797] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 __xocl_subdev_destroy: Destroy subdev mig, cdev 0000000000000000
> [  741.069856] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_refresh_addrs: memcalib @ ffffa519c6a11000
> [  741.069859] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: section 6 offset: 25105704, size: 328
> [  741.069872] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: section 6 offset: 25105704, size: 328
> [  741.069884] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_parse_bitstream_axlf_section: icap_parse_bitstream_axlf_section kind 6, err: 0
> [  741.069887] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: section 8 offset: 25106032, size: 408
> [  741.069891] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_parse_bitstream_axlf_section: icap_parse_bitstream_axlf_section kind 8, err: 0
> [  741.069893] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: could not find section header 20
> [  741.069896] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_parse_bitstream_axlf_section: icap_parse_bitstream_axlf_section kind 20, err: -22
> [  741.069898] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: could not find section header 11
> [  741.069901] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 axlf_set_freqscaling: set 4 freq, data: 300, kernel: 500, sys: 0, sys1: 0
> [  741.069924] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 axigate_freeze: freeze gate ep_pr_isolate_ulp_00 level 2
> [  741.069926] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_freeze_axi_gate: level 2 returns 0
> [  741.069929] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling_impl: Clock: 0, Current: 300 MHz, New: 300 Mhz,  Force: 0
> [  741.069931] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling_impl: current freq and new freq are the same, skip updating.
> [  741.069934] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling_impl: Clock: 1, Current: 500 MHz, New: 500 Mhz,  Force: 0
> [  741.069935] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling_impl: current freq and new freq are the same, skip updating.
> [  741.069937] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling_impl: returns 0
> [  741.069948] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 axigate_free: free gate ep_pr_isolate_ulp_00 level 2
> [  741.069950] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_free_axi_gate: level 2 returns 0
> [  741.069952] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_ocl_freqscaling: level: 2 return: 0
> [  741.069953] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 set_freqs: returns 0
> [  741.069955] xclmgmt 0000:af:00.0: clock.m.23068672 ffff912ab0e97410 clock_update_freq: verify: 0 ret: 0.
> [  741.069957] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 ulp_clock_update: returns: 0
> [  741.069959] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_refresh_clock_freq: ret: 0
> [  741.069961] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_freeze_axi_gate: freezing CL AXI gate
> [  741.069967] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 axigate_freeze: freeze gate ep_pr_isolate_ulp_00 level 2
> [  741.069969] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 get_axlf_section_hdr: section 0 offset: 15816, size: 25089884
> [  741.069971] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_download_hw: found second stage bitstream of size 0x17ed75c
> [  741.069973] xclmgmt 0000:af:00.0: **_icap.m.16777216 ffff912ab0e91c10 icap_download_hw: Dowload bitstream failed_**
> [  741.069978] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_download_hw: icap_download_hw, err = -22
> [  741.069980] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_free_axi_gate: freeing CL AXI gate
> [  741.069990] xclmgmt 0000:af:00.0:  ffff911ab9f2d0b0 axigate_free: free gate ep_pr_isolate_ulp_00 level 2
> [  741.069992] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 __icap_xclbin_download: ret: -22
> [  741.069994] xclmgmt 0000:af:00.0: icap.m.16777216 ffff912ab0e91c10 icap_download_bitstream_axlf: icap_download_bitstream_axlf err: -22
> [  741.070920] xclmgmt 0000:af:00.0: mailbox.m.15728640 ffff912ab0e94410 mailbox_post_response: posting response for: 7 via HW
> [  741.071060] xocl 0000:af:00.1: **_icap.u.16777216 ffff912aaf541010 __icap_peer_xclbin_download: peer xclbin download err: -22_**
> [  741.071066] xocl 0000:af:00.1: icap.u.16777216 ffff912aaf541010 icap_download_bitstream_axlf: icap_download_bitstream_axlf err: -22
> [  741.071071] xocl 0000:af:00.1:  ffff912ab9c140b0 exec_reset: exec_reset(0) cfg(0)
> [  741.071073] xocl 0000:af:00.1:  ffff912ab9c140b0 exec_reset: exec_reset resets
> [  741.071076] xocl 0000:af:00.1:  ffff912ab9c140b0 exec_reset: exec->xclbin(8ce40966-a276-4968-ab5c-8f9d09919e86),xclbin(00000000-0000-0000-0000-000000000000)
> [  741.071082] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: Topology count = 8, data_length = 320
> [  741.071094] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: bank0
> [  741.071096] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x0
> [  741.071097] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x400000000
> [  741.071099] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:1
> [  741.071100] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:1
> [  741.071102] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: bank1
> [  741.071103] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x400000000
> [  741.071105] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x400000000
> [  741.071106] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:1
> [  741.071107] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:1
> [  741.071109] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: bank2
> [  741.071110] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x800000000
> [  741.071111] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x400000000
> [  741.071113] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:1
> [  741.071114] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071115] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: bank3
> [  741.071117] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0xc00000000
> [  741.071118] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x400000000
> [  741.071119] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:1
> [  741.071120] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071122] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: PLRAM[0]
> [  741.071123] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x1000000000
> [  741.071125] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x20000
> [  741.071126] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:2
> [  741.071127] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071128] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: PLRAM[1]
> [  741.071130] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x1000020000
> [  741.071131] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x20000
> [  741.071132] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:2
> [  741.071134] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071135] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: PLRAM[2]
> [  741.071137] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x1000040000
> [  741.071138] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x20000
> [  741.071139] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:2
> [  741.071141] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071142] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Memory Bank: PLRAM[3]
> [  741.071143] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Base Address:0x1000060000
> [  741.071145] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Size:0x20000
> [  741.071146] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Type:2
> [  741.071147] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   Used:0
> [  741.071149] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: Allocating Memory Bank: bank0
> [  741.071151] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   base_addr:0x0, total size:0x400000000
> [  741.071152] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: Found a new memory region
> [  741.071161] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: drm_mm_init called
> [  741.071162] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: Allocating Memory Bank: bank1
> [  741.071164] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem:   base_addr:0x400000000, total size:0x400000000
> [  741.071165] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: Found a new memory region
> [  741.071173] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_init_mem: drm_mm_init called
> [  741.071176] xocl 0000:af:00.1:  **_ffff912ab9c140b0 xocl_read_axlf_helper: Failed to download xclbin, err: -22_**
> [  741.266018] [drm] client exits pid(8513)
> [  741.266028] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_drvinst_close: CLOSE 2
> [  741.266033] xocl 0000:af:00.1:  ffff912ab9c140b0 xocl_drvinst_close: NOTIFY 00000000dbef9e1e

**Comment by randyh62** [comment]
I am not sure what the specific problem is based on the approach you have taken. However, you can specify the TARGET=hw_emu and the PLATFORM=xilinx_u200_gen3x16_xdma_1_202110_1 in the Makefile command line:

make TARGET=hw_emu PLATFORM=xilinx_u200_gen3x16_xdma_1_202110_1
v++ --kernel vadd --platform xilinx_u200_gen3x16_xdma_1_202110_1 -t hw_emu -s -g -c -o vadd.xo vadd.cpp
v++ --kernel wide_vadd --platform xilinx_u200_gen3x16_xdma_1_202110_1 -t hw_emu -s -g -c -o wide_vadd.xo wide_vadd.cpp
v++ --kernel resize_accel_rgb --platform xilinx_u200_gen3x16_xdma_1_202110_1 -t hw_emu -s -g -I. -I./Vitis_Libraries/vision/L1/include --config vision_config.ini -c -o resize_rgb.xo resize_rgb.cpp
v++ --kernel resize_blur_rgb --platform xilinx_u200_gen3x16_xdma_1_202110_1 -t hw_emu -s -g -I. -I./Vitis_Libraries/vision/L1/include --config vision_config.ini -c -o resize_blur.xo resize_blur.cpp
v++ -l --platform xilinx_u200_gen3x16_xdma_1_202110_1 -t hw_emu -s -g --jobs 47 --config profile.ini --config connectivity_u200.ini -o alveo_examples.xclbin vadd.xo wide_vadd.xo resize_rgb.xo resize_blur.xo --remote_ip_cache ./ip_cache

Can you try this to see if you can run hw_emu?

**Comment by xooxit** [comment]
Thanks for reply
 
I have tried to specify TARGET and PLATFORM in the Makefile command line and 
it ends up like below.

```
$ make TARGET=hw_emu PLATFORM=xilinx_u250_xdma_201830_2
v++ --kernel vadd --platform /opt/xilinx/platforms//xilinx_u250_xdma_201830_2/xilinx_u250_xdma_201830_2.xpfm -t hw_emu -s -g -c -o vadd.xo vadd.cpp

......

Successfully wrote (25126053 bytes) to the output file: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/alveo_examples.xclbin
Leaving xclbinutil.
INFO: [v++ 60-1441] [11:11:49] Run run_link: Step xclbinutil: Completed
Time (s): cpu = 00:00:00.14 ; elapsed = 00:00:00.25 . Memory (MB): peak = 1340.742 ; gain = 0.000 ; free physical = 120061 ; free virtual = 128288
INFO: [v++ 60-1443] [11:11:49] Run run_link: Step xclbinutilinfo: Started
INFO: [v++ 60-1453] Command Line: xclbinutil --quiet --force --info /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/alveo_examples.xclbin.info --input /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/alveo_examples.xclbin
INFO: [v++ 60-1454] Run Directory: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/_x/link/run_link
INFO: [v++ 60-1441] [11:11:49] Run run_link: Step xclbinutilinfo: Completed
Time (s): cpu = 00:00:00.41 ; elapsed = 00:00:00.49 . Memory (MB): peak = 1340.742 ; gain = 0.000 ; free physical = 120062 ; free virtual = 128288
INFO: [v++ 60-1443] [11:11:49] Run run_link: Step generate_sc_driver: Started
INFO: [v++ 60-1453] Command Line: 
INFO: [v++ 60-1454] Run Directory: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/_x/link/run_link
INFO: [v++ 60-1441] [11:11:49] Run run_link: Step generate_sc_driver: Completed
Time (s): cpu = 00:00:00 ; elapsed = 00:00:00.01 . Memory (MB): peak = 1340.742 ; gain = 0.000 ; free physical = 120062 ; free virtual = 128289
INFO: [v++ 60-244] Generating system estimate report...
INFO: [v++ 60-1092] Generated system estimate report: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/_x/reports/link/system_estimate_alveo_examples.xtxt
INFO: [v++ 60-586] Created alveo_examples.xclbin
INFO: [v++ 60-1307] Run completed. Additional information can be found in:
        Guidance: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/_x/reports/link/v++_link_alveo_examples_guidance.html
        Steps Log File: /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/_x/logs/link/link.steps.log

INFO: [v++ 60-2343] Use the vitis_analyzer tool to visualize and navigate the relevant reports. Run the following command. 
    vitis_analyzer /home/lab/yong/fpga-project/tutorial/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_emu_src/alveo_examples.xclbin.link_summary 
INFO: [v++ 60-791] Total elapsed time: 0h 3m 37s
INFO: [v++ 60-1653] Closing dispatch client.
```

**Comment by randyh62** [comment]
This looks like the build of the xclbin was successful. You still need to run the the application to run the host and xclbin in emulation mode. For example:
```
   setenv XCL_EMULATION_MODE hw_emu
    ./00_load_kernels
```

**Comment by xooxit** [comment]
Thanks for reply

NOw works well, it's the issue of unsetting XCL_EMULATION_MODE environment variable and emconfig.json file
