### ISSUE TITLE
ERROR: [v++ 60-602] 

### ISSUE THREAD

**Issue by canozcifci** [Xilinx/Vitis-Tutorials#143]
Hi,

I am facing a problem when i build vector addition application project.  I can build with Emulation-SW, but when I tried to build with Emulation-HW or Hardware. I got the error:
ERROR: [v\+\+ 60-602] Source file does not exist: /Xilinx/kv260-vitis/platforms/ws/add_vector_00_system_hw_link/Emulation-HW/binary_container_1.xclbin
INFO: [v\+\+ 60-1662] Stopping dispatch session having empty uuid.
INFO: [v\+\+ 60-1653] Closing dispatch client.
makefile:38: recipe for target 'package' failed
make: *** [package] Error 1.

Thanks
John

**Comment by imrickysu** [comment]
Hi John,

binary_container_1.xclbin is the output of v++ link. I guess your v++ link doesn't complete successfully. Could you check whether there are any error information?

**Comment by canozcifci** [comment]
Hi Ricky, 

Thanks for the quick reply. I followed the instructions "Vitis 2021.1 Embedded Platform for Zybo-Z7-20" by Mohammad

[here](https://highlevel-synthesis.com/2021/08/15/vitis-2020-1-embedded-platform-for-zybo-z7-20/)

Can you tell me where i can find the necessary error info for v++ link?

Thanks
John

**Comment by imrickysu** [comment]
Hi @canozcifci , if you select the hw_link component under the system project, it will show you related building info. 

When selecting the system project, it only shows you the packaging related info.

**Comment by Seyyidosman** [comment]
Hi, I am also facing with this problem. Please help me!

Seyyid

**Comment by mor2810** [comment]
any fix for that issue ?
i have exactly the same error

**Comment by AnusheelXilinx** [comment]
If there is an error in the Vitis build run, user may encounter this issue. Please check the log files to understand the failure. 
Please test the latest tutorial steps and let us know if you still this issue while building the design. 

We do not see this issue in the internal testing. 

Thanks
Anusheel

**Comment by jesko42** [comment]
Hi together, I face the same or similar problem (and I am wondering that this is not working if all is properly tested):

* Fresh install: Ubuntu 24.04LTS
* Fresh install: Vitis 2025.1
* Fresh clone: https://github.com/Xilinx/Vitis-HLS-Introductory-Examples.git

In Vitis open the terminal, goto folder:
Vitis-HLS-Introductory-Examples/Task_level_Parallelism/Data_driven/simple_data_driven

Start:
vitis-run --mode hls --tcl run_hls.tcl

Output:
****** vitis-run v2025.1 (64-bit)
  **** SW Build 6137779 on 2025-05-21-18:10:03
  **** Start of session at: Wed Sep  3 16:24:56 2025
    ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
    ** Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.

ERROR: problem reading data directory /tools/Xilinx/2025.1/Vivado/data/deca/UltraScale/Explore : boost::filesystem::status: Structure needs cleaning: "/tools/Xilinx/2025.1/Vivado/data/deca/UltraScale/Explore/o_RR_o_Ex_p_SBSl_ppp_AgEx_r_NTR-o_ExSeAr_p_ASLL_ppp_AgEx_r_NTR"
INFO: [vitis-run 60-1662] Stopping dispatch session having empty uuid.



==> Who can help ?
