### ISSUE TITLE
next step click error

### ISSUE THREAD

**Issue by s0897918** [Xilinx/Vitis-Tutorials#146]
Hi there,

At the bottom of this page, there is an error when I click the hyperlink: Click here to Review the Host and Kernel Code, the page didn't jump to the next page at all.

**Comment by imrickysu** [comment]
Thanks @s0897918 .

Hi @randyh62 , could you update this? https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/Getting_Started/Vitis/Part2.md

**Comment by randyh62** [comment]
I have corrected it here and in swm

**Comment by imrickysu** [comment]
Fixed by ad53e07d22c55e95ff95182784a859df9ec771ad
