### ISSUE TITLE
Convolution-Tutorial: Caught Exception during hw_emu build

### ISSUE THREAD

**Issue by cabreraam** [Xilinx/Vitis-Tutorials#15]
Before I start, I will note that I am using the Deployment Target Platofrm version:
`xilinx_u250_xdma_201830_2` on my Alveo U250. 

When trying to run hardware emulation [in this step](https://github.com/Xilinx/Vitis-Tutorials/blob/master/docs/convolution-tutorial/baseline.md), I see the following log info:

```
INFO: [HW-EM 06-0] Waiting for the simulator process to exit
INFO: [HW-EM 06-1] All the simulator processes exited successfully
ERROR: [EMU 60-601]  Exception Caught - Failed with the command REMOVE operation at the Line Number: 1434
```

I use `ctrl+c` to kill the process but then I don't get any profiling data when using `vitis_analyzer`, i.e., there is no _Kernel Execution_ section, or _Kernels to Global Memory_ section.

Any help would be welcome!

**Comment by rwarmstr** [comment]
@cabreraam Sincere apologies for the delay responding on this one, as you can see we've made pretty substantial changes to the tutorial structure. If you still see similar issues can you please re-open this?

Thanks!
