### ISSUE TITLE
Does Vitis support VCK5000? 

### ISSUE THREAD

**Issue by whyaysd** [Xilinx/Vitis-Tutorials#153]
Does Vitis support VCK5000 platform? 

Could you please give me an example project targeting vck5000?

**Comment by Premduth** [comment]
@allyzhou  can you comment?

**Comment by whyaysd** [comment]
@Premduth  @allyzhou  Could you please give me some advice?

**Comment by allyzhou** [comment]
@whyaysd depends on different versions of VCK5000 boards and platforms, Vitis provide different levels of support. If you have VCK5000 for Vitis AI, the demo are publically accessible at https://github.com/Xilinx/Vitis-AI. Other than Vitis AI on VCK5000, we don't have public accessible tutorials/examples. We do have a plan to release a Vitis tutorial on VCK5000, but it will only be an EA version through a secure site like a lounge.

**Comment by whyaysd** [comment]
Thanks for your information.

I am participating in the Adaptive Computing Challenge 2021 hosted by Xilinx: https://www.hackster.io/contests/xilinxadaptivecomputing2021. I need to use VCK5000 to finish my work, and I need to use Vitis to implement my functions. 

I have got the EA version of VCK5000 from xilinx and I have access to the secure site: https://www.xilinx.com/member/vck5000-aie.html#overview.

Taking those into consideration, could you please help me to solve those problems or just give me a demo?


Thank you

**Comment by whyaysd** [comment]
@Premduth Could you please give me some help?

**Comment by allyzhou** [comment]
Vitis flow is supported on VCK5000 Prod card,  https://www.xilinx.com/products/boards-and-kits/vck5000.html

**Comment by ombhilare999** [comment]
@allyzhou when will be vitis flow supporting vck5000 es1 card?

**Comment by Premduth** [comment]
There are no plans to support a Vitis flow for the es1 card. In order to use the Vitis flow you have to be on the VCK5000 production card.

**Comment by tiny-dentist** [comment]
@Premduth when you mean no plans to support Vitis flow for the ES1 card, do you mean there will be no examples provided for it? If I remember correctly the ES1 card supports Vitis 2020.2 and there are plans for updated shells which will allow it to be used with Vitis 2021.1.1 .

**Comment by Premduth** [comment]
Correct no new Vitis examples will be provided for the es1 card.

**Comment by tiny-dentist** [comment]
@Premduth  So just confirming it is possible to access the AIE kernel and implement Hardware accelerated Pre-Post processing with Vitis 2020.2 but there are no tutorials present for it. Is this correct?

**Comment by allyzhou** [comment]
no plan to update ES1 platform to make it work with Vitis newer version, and we have no plan to provide any Vitis end-to-end design examples on VCK5000 ES1 platform.

**Comment by ombhilare999** [comment]
okay does that mean using the current shell I can access AIE cores using vitis 2020.2 version?
Can we follow the vck5000 production or alveo card's end-to-end example and replicate the results for vck5000 es1 card on current shell + vitis 2020.2 version?

**Comment by allyzhou** [comment]
I don't think your shell version can work with 2020.2 Vitis, if you're using Vitis AI, the download page will provide you the detailed Vitis, XRT, and platform version, please strictly follow that. Other than what we announced, we have no plan and no resource for enough regression test run to guarantee the other combinations of tools and platforms will work.

**Comment by gustandil** [comment]
Hi, I'm trying to understand the limitation of ES1 boards.
We installed a few months ago and test VCK5000-ES1. 
Now we tried to reproduce the examples, and the reference from lounge was "disappeared".
I googled without results of the former information. Is available?

Best Regards, GS

**Comment by Premduth** [comment]
VCK5000-ES1 cards and pretty much any ES1 cards are only supported via lounge access. Please contact your nearest sales office for instructions to the lounge.
