### ISSUE TITLE
launch_emulator: command not found

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#163]
When I input the order "./launch_hw_emu.sh", it dispay as follows:
![1642162481(1)](https://user-images.githubusercontent.com/71826731/149513945-20c27718-5d99-4709-9a19-814c0ad83df1.png)

**Comment by randyh62** [comment]
It looks like the `$PATH` is not setup properly as the `launch_emulator` command should be accessible from the Vitis installation. This is usually configured when the environment is setup with the `settings.sh` script. The `launch_hw_emu.sh `script is generated by the v++ command during the build process, and should not need to be run under `sudo`.

**Comment by Candice-Yin** [comment]
@randyh62 Hi! I set up the $PATH as follows:
![359e025d501dba521d73f82089a8997](https://user-images.githubusercontent.com/71826731/149613692-9ca0b15b-88f7-4bfb-bdeb-c3e619c9462a.png)
![bfead91e94d6f370755a47d67ef00e8](https://user-images.githubusercontent.com/71826731/149613700-d5ef51bd-d995-4bf7-875a-4b1402eb57de.png)
The strange thing is that I succeeded in this step before.

**Comment by randyh62** [comment]
It looks like your setup is correct. Not sure why it would work one time and not the next.  Can you type "which launch_emulator" and see what is returned?

**Comment by Candice-Yin** [comment]
> It looks like your setup is correct. Not sure why it would work one time and not the next. Can you type "which launch_emulator" and see what is returned?

I find that the problem is about user rights. Thank you. @randyh62
