### ISSUE TITLE
g++: error: unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by jiajiahao0619** [Xilinx/Vitis-Tutorials#186]
I am running the 2021.2 branch. 
It is normal until run the make host command. It is so kindly that tell me how to fix it? or it doesn't matter for the project?

![image](https://user-images.githubusercontent.com/30894220/153839183-6ac6b9b6-88f4-46ae-8d9c-3bb60e9fced3.png)

**Comment by imrickysu** [comment]
Hi @jiajiahao0619 , Vitis doesn't ship `g++` in its installer. Host application compilation uses the system default GCC/G++.
It's possible that on CentOS/RHEL, default GCC doesn't support C++14. If you'd like to use `-std=c++14`, please upgrade your system GCC version.

**Comment by imrickysu** [comment]
Hi @jiajiahao0619 , BTW, if you're working on an embedded application, this error may indicate that you didn't setup toolchain and SYSROOT properly. Please check the environment setup guidance of the tutorial you are referring to.

**Comment by jiajiahao0619** [comment]
Thanks @imrickysu  It is really helpful for me. it is normal now.
