### ISSUE TITLE
Error Vitis Analyzer - tutorial: 13-aie-performance-analysis

### ISSUE THREAD

**Issue by nielsvanetten** [Xilinx/Vitis-Tutorials#193]
https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/AI_Engine_Development/Feature_Tutorials/13-aie-performance-analysis/aie_execution_measurement.md

When opening the trace file tap in vitis_analyzer I receive the error: /tmp/vitis_analyzer/[user]/system.wdb is not a valid trace report file.
Using fedora release 34.
Vitis 2021.2.

**Comment by nielsvanetten** [comment]
seems there is some weird mapping going on, if i make that directory and put the system.wdb and .wcfg files in that directory it works. Is there any way to configure the vitis_analyzer where it looks for these files?

**Comment by AlphaBu** [comment]
Hi, @nielsvanetten Could you try run following command before opening Vitis Analyzer: 
**vcdanalyze --vcd=foo.vcd --wdb --ctf**
Then see if this issue is still there? 
It can not be reproduced for me. Not sure if it's related to Linux version.

**Comment by nielsvanetten** [comment]
it work when i do the command **vcdanalyze --vcd=foo.vcd --wdb** and then put the files in this tmp folder. Not sure why vitis analyzer is looking in that folder for the file and how i can change it.

**Comment by xflorentw** [comment]
I am wondering if this issue is not due to the workdir not set (this is why the output is sent to /temp)

![image](https://user-images.githubusercontent.com/44667405/156346938-fab89b73-2f69-475b-8fbb-a5a9ba734957.png)

**Comment by nielsvanetten** [comment]
that did the trick. Thank you!

**Comment by xflorentw** [comment]
Great

@AlphaBu Can you update the Makefile accordingly?
