### ISSUE TITLE
PFM: explain more about platform_repo in step4

### ISSUE THREAD

**Issue by imrickysu** [Xilinx/Vitis-Tutorials#200]
https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/Vitis_Platform_Creation/Introduction/03_Edge_VCK190/step4.md says:

Select the directory that [step3](https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/Vitis_Platform_Creation/Introduction/03_Edge_VCK190/step3.md) generates. For example ref_files/step3_pfm/platform_repo

But in step3, there no description mentions this directory. It's generated by https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/Vitis_Platform_Creation/Introduction/03_Edge_VCK190/ref_files/step3_pfm/xsct_create_pfm.tcl#L22. 

Please consider unify the platform output directory name in the step3 and step4 description. If they can't be unified, please mention their names in step4.

**Comment by sven2314** [comment]
Hi,  Ricky 
I filed a PR about unifying the platform repo.

**Comment by imrickysu** [comment]
Fix with https://github.com/Xilinx/Vitis-Tutorials/pull/209
