### ISSUE TITLE
PFM ZCU104: incorrect system-user.dtsi path

### ISSUE THREAD

**Issue by imrickysu** [Xilinx/Vitis-Tutorials#201]
https://github.com/Xilinx/Vitis-Tutorials/blob/2021.1/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step2.md says:

You can also add your custom device tree modifications to project-spec/meta-user/system-user.dtsi

This path is incorrect. It might be project-spec/meta-user/recipes-bsp/device-tree/files/system-user.dtsi

Please confirm and update.

**Comment by sven2314** [comment]
Hi, Ricky
I confirmed the <project-spec/meta-user/recipes-bsp/device-tree/files/> directory is right. And filed a PR to 2021.1 and 2021.2 version.

**Comment by imrickysu** [comment]
2021.2 fix: https://github.com/Xilinx/Vitis-Tutorials/pull/209
