### ISSUE TITLE
explanation confusing example: 02-using-gmio 

### ISSUE THREAD

**Issue by nielsvanetten** [Xilinx/Vitis-Tutorials#215]
At the bottem of: https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/AI_Engine_Development/Feature_Tutorials/02-using-gmio/single_aie_gmio.md

Its stated:
```
After the package is done, run the following commands in the Linux prompt after booting Linux from an SD card:

export XILINX_XRT=/usr
cd /mnt/sd-mmcblk0p1
./host.exe a.xclbin
```
When working with the VCK190, do they mean booting the VCK190 with a petalinux version installed on the SD card and then running these commands from your own Linux PC ?

**Comment by imrickysu** [comment]
Please run these commands on VCK190 Linux.

**Comment by imrickysu** [comment]
Hi @AlphaBu , `export XILINX_XRT=/usr` is not needed for embedded acceleration. Could you update the instructions while clarifying this issue?
