### ISSUE TITLE
i can not find  rootfs.ext4 in zcu104_custom_plnx/images

### ISSUE THREAD

**Issue by Ydrsmart** [Xilinx/Vitis-Tutorials#216]
i can not find the file named rootfs.ext4 in zcu104_custom_plnx/images/  when i follow the step4。

**Comment by imrickysu** [comment]
rootfs.ext4 is generated by step 2 PetaLinux settings
- Add EXT4 rootfs support (Optional but recommended)
- Build PetaLinux Images

Please check your PetaLinux project settings.

**Comment by imrickysu** [comment]
Hi @sven2314 , maybe we should remove the comment of "Optional but recommended" for "Add EXT4 rootfs support" because the following instructions depends on ext4.

**Comment by imrickysu** [comment]
fixed in PR #235
