### ISSUE TITLE
Emulation-HW stalls for Hw_Accel\Introduction\03-Algorithm_Acceleration\docs\module1_baseline

### ISSUE THREAD

**Issue by AzzHub** [Xilinx/Vitis-Tutorials#219]
I import the project according to the readme. I can run Emulation-SW correctly and fast,  while the Emulation-HW is very slow even runs longer than ten hours!
The only step defferent to the readme is I add a  Program Arguments : `-xclbin /home/module1baseline/cholesky_system/Emulation-SW/binary_container_1.xclbin`. 
PS1: Emulation-HW is very slow even I add  Argument:  `-M 1 -N 1`.
PS2: The Debug can't run correctly while Emulation-HW is active with showing 

> No source available for "main() at 0x555555556c10"

**Comment by AzzHub** [comment]
I added some printf for checking, and found that:
    the program stalls at `q.finish()` in line 172(in "test.cpp")
   ```
// Data transfer from host buffer to device buffer
    std::vector<std::vector<cl::Event> > kernel_evt(2);
    kernel_evt[0].resize(1);
    kernel_evt[1].resize(1);

    std::vector<cl::Memory> ob_io;
    ob_io.push_back(buffer[0]);

    q.enqueueMigrateMemObjects(ob_io, 0, nullptr, &kernel_evt[0][0]); // 0 : migrate from host to dev
    q.finish();
    std::cout << "INFO: Finish data transfer from host to device" << std::endl;
```

**Comment by randyh62** [comment]
I have tested it and it took about 15 minutes to complete the hw_emu run as you can see from the attached screenshot. The build itself took one hour 8 minutes as you can also see reported toward the top. 

Perhaps there is an issue with your system memory or OS? Can you provide a few details about the configuration of your environment?
![cholesky-module1-baseline-hw_emu](https://user-images.githubusercontent.com/42045079/159371452-348ff1ab-33b8-438c-bbb2-2e258ab536dd.png)

**Comment by AzzHub** [comment]
I run this on a server of my school. I am new at vitis,  could you tell me what configuration should I provide?
And I think this issue may be caused by some details I haven't notice. How should I check that? Thank you very much

**Comment by randyh62** [comment]
Since you are new to Vitis, perhaps you could start with the https://github.com/Xilinx/Vitis-Tutorials/tree/2021.2/Getting_Started/Vitis tutorial? Focusing on the U200 for the Data Center acceleration card. See if you can get the hw_emu build to run for that tutorial?

**Comment by AnusheelXilinx** [comment]
Closing the thread as there are no open concerns.

Thanks
Anusheel
