### ISSUE TITLE
2021.2 - AIE - design tutorial - 09 post-link-recompile - VitisIDE_flow . step 16 needs updating?

### ISSUE THREAD

**Issue by delorytheape** [Xilinx/Vitis-Tutorials#220]
Hi,
While following https://github.com/Xilinx/Vitis-Tutorials/tree/2021.2/AI_Engine_Development/Design_Tutorials/09-post-link-recompile/VitisIDE_Flow.md, it seems that Phase1, step 16 may need updating (??) 
ie. For Vitis 2021.2 there appears to be no column "PL Kernel in AIE Graph" in the "Hardware Functions" of the PL project (unless I have done something incorrect ?? but I think I have followed everything else correctly).
When I try to build the whole project (Cosim1_system_hw_link [pl] | Build Project), it fails with various errors including;
ERROR: [CFGEN 83-2284] No stream resources found that can accomodate compute unit "polar_clip_1.in_sample"
which I assume is related to step 16  that can no longer be performed. 

The makefile version of the tutorial completed without error.

**Comment by delorytheape** [comment]
For anyone interested: The template example included in 2021.2 (AI Engine, PL and PS System Design) is basically the same, but works correctly (just skip step 16). The template example uses a slightly different graph that does not include the PL kernel 'polar_clip', but rather has two additional ports to connect to the PL kernel.

**Comment by OTremois** [comment]
The Lab has been completely revisited in 2022.1.
polar_clip is out of the graph and the new programming model is used.
A new use case has been added which does not need an intermediate platform to be created.
