### ISSUE TITLE
Vitis Platform Creation Tutorial for ZCU104: PYNQ integration

### ISSUE THREAD

**Issue by emanueledelsozzo** [Xilinx/Vitis-Tutorials#225]
Hello, I went through Vitis Platform Creation Tutorial for ZCU104 with Vitis 2020.2 and it works fine. 
I would like to use this platform to build C/C++ executables and xclbins and run them on PYNQ images.
I tried to use the vadd executable and xclbin generated within this tutorial with a PYNQ 2.7 image on the ZCU104 and the executable stalls waiting for the end of the kernel computation. Probably this is not the right flow for PYNQ images. 

[QUESTION] Would it be possible to modify the petalinux image generated within this tutorial to build a PYNQ image directly?

Thank you!

**Comment by imrickysu** [comment]
Hi @emanueledelsozzo ,

As long as xrt is included in the rootfs, you're free to customize your PetaLinux image.

If the xclbin and executables are the same, only SW or OS is different, you may check whether the device tree is correct in your Pynq image. XRT needs ZOCL node in device tree.

**Comment by emanueledelsozzo** [comment]
Hi @imrickysu and thank you for your reply.
I tried to rebuild the PYNQ image for ZCU104 and I noticed that both XRT an ZOCL are included within the PetaLinux configuration. So, I suppose that is not the problem.

BTW, I noticed that in the makefile for the [PetaLinux step](https://github.com/Xilinx/Vitis-Tutorials/blob/2020.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/ref_files/step2_petalinux/Makefile) , there is no ZOCL in the PetaLinux configuration, and just one command for xrt. Does this command:
`echo 'CONFIG_packagegroup-petalinux-xrt=y'`
include all the necessary components to make xrt work?
The makefile for PYNQ images explicitly adds xrt, zocl, and so on to PetaLinux configuration. Could this difference cause the problems I am facing?

**Comment by imrickysu** [comment]
Hi @emanueledelsozzo , [packagegroup-petalinux-xrt includes zocl for 2020.2.](https://github.com/Xilinx/meta-petalinux/blob/rel-v2020.2/recipes-core/packagegroups/packagegroup-petalinux-xrt.bb). In later releases ZOCL becomes Runtime dependency (RDEPENDS) of XRT.
If XRT has issues, your program will report errors in dmesg.

It still looks like an interrupt configuration issue to me. Did you use the same device tree file for both images?

If this doesn't solve your question, suggest to ask this question in Xilinx Forums https://support.xilinx.com/. You will get more support there.

**Comment by emanueledelsozzo** [comment]
Hi @imrickysu, thank you for the clarification about packagegroup-petalinux-xrt.
I'm not sure it is an interrupt configuration issue. I tried to run the kernel, wait some seconds, and then read the output buffer (if I try to wait for the kernel completion, it waits indefinitely). The content of the output buffer is all zeros, just like after its allocation. So, it seems that the kernel does not even start its execution.

I have written on the PYNQ forum, but I did get any answer yet. Here the [link](https://discuss.pynq.io/t/vitis-embedded-platform-compliant-with-pynq/3942).

**Comment by imrickysu** [comment]
Hi @emanueledelsozzo , Xilinx technical support team monitors the Xilinx Forums https://support.xilinx.com/.
The Pynq Forum you posted on seems less active than Xilinx Forums.

You can also ask about how to debug acceleration applications in Xilinx Forums. With the help of gdb and Vitis kernel debug features, you can dump the run time waveform and analyze the issue. I understand it should not be application developer's duty to debug the application in such a low level, but the platform developer should ensure the kernel works and these debugging techniques are required.

**Comment by emanueledelsozzo** [comment]
Hi @imrickysu, sorry for my late response but I do not receive notifications when you reply. I got an answer on the PYNQ Forum and they say that the Vitis Embedded Platform flow is not currently supported on PYNQ. So I think I have to wait for future releases.
Thank you anyway!
