### ISSUE TITLE
02-super_sampling_rate_fir/Utils

### ISSUE THREAD

**Issue by nielsvanetten** [Xilinx/Vitis-Tutorials#231]
after following the tutorial and executing: `source InitPythonPath`, and than executing `sudo GenerateStreamGUI` I get the error `sudo: GenerateStreamsGUI: command not found`

in `echo $PATH` and `echo $PYTHONPATH` however i do see the path to the util folder.

I use Ubuntu LTS 20.04.4

**Comment by nielsvanetten** [comment]
i basically got it working by removing 

```
echo " "
echo "Stream Content Generation"
echo " "

python - <<END
```

and than execute `python3 GenerateStreamsGUI`

**Comment by AnusheelXilinx** [comment]
Closing the thread as there are no open concerns.

Thanks
Anusheel
