### ISSUE TITLE
Possible Data Corruption in Example Design_Tutorials/06-fft2d_AIEvsHLS

### ISSUE THREAD

**Issue by K-Wu** [Xilinx/Vitis-Tutorials#233]
When running `aiesimulator` on `Design_Tutorials/06-fft2d_AIEvsHLS`, I continue to get the following messages.

> WARNING : Line skipped, invalid number of data samples on line, got 1 expected 8

To work this around, I replaced `1.0` with `1` in the two input files `Design_Tutorials/06-fft2d_AIEvsHLS/AIE/design/aie_src/aiesim_data/input0.txt` and `Design_Tutorials/06-fft2d_AIEvsHLS/AIE/design/aie_src/aiesim_data/input1.txt`. This suppressed the aforementioned warning messages.

I still want to check if the dataset files content is correct and understand the best way to fix this. Thanks!

**Comment by imrickysu** [comment]
Hi @JithinPillai, could you help with this question?

**Comment by JithinPillai** [comment]
Hi @imrickysu,
It is happening due to data being provided for the cint16 design is same as that for cfloat, I will fix that

**Comment by JithinPillai** [comment]
Hi @K-Wu,
The issue should be fixed now!
Sorry for the delay the I was out of office due to some personal matters.
Please have a look.

Regards
Jithin

**Comment by K-Wu** [comment]
Thank you @JithinPillai  for addressing this issue! I have stopped working on the project using this for a while but I also believe we can close this issue now as it is fixed. Thanks again!
