### ISSUE TITLE
[XRT] WARNING: Profiling may contain incomplete information.

### ISSUE THREAD

**Issue by beenleyi** [Xilinx/Vitis-Tutorials#24]
Hi, I am running the example in the tutorial https://github.com/Xilinx/Vitis-Tutorials/tree/master/Getting_Started/Vitis with u200.

I got this message after run app.exe
```
 $ ./app.exe
INFO: Found Xilinx Platform
INFO: Loading 'vadd.xclbin'
ERROR : [SW-EM 10] Please make sure that the XILINX_VITIS environment variable is set correctly
XRT build version: 2.7.766
Build hash: 19bc791a7d9b54ecc23644649c3ea2c2ea31821c
Build date: 2020-08-17 16:52:05
Git branch: 2020.1_PU1
PID: 2614
UID: 1000
[Tue Dec 1 14:39:05 2020 GMT]
HOST: iu-virtual-machine
EXE: /home/iu/work/workspace/example/u200/sw_emu/app.exe
[XRT] WARNING: Profiling may contain incomplete information. Please ensure all OpenCL objects are released by your host code (e.g., clReleaseProgram()).
```

The Vitis environment variables have been set and I can run v++ anywhere, so I don't think the problem is the env.

And how about the XRT warning? Should I add clReleaseProgram() in the host.cpp?

Thanks a lot.

**Comment by rwarmstr** [comment]
Hi @beenleyi, I'm not seeing that on our end and am wondering if perhaps this might be an XRT installation issue. It has been some time though (and I apologize for that!), so for now I'll close this, but please re-open it or file a new issue if you continue to see it.
