### ISSUE TITLE
Vitis Getting Started Tutorial - Part4 - command has wrong script name as argument

### ISSUE THREAD

**Issue by GianlucaGaroia** [Xilinx/Vitis-Tutorials#241]
In the "Targeting Hardware Emulation" section:
https://github.com/Xilinx/Vitis-Tutorials/blob/2022.1/Getting_Started/Vitis/Part4-embedded_platform.md#targeting-hardware-emulation

The last v++ build command has "run_app.sh" as final argument - this is wrong name, the command fails, the correct name (from github sources) is run_hw_emu.sh

Same error in the successive "Targeting Hardware" section:
https://github.com/Xilinx/Vitis-Tutorials/blob/2022.1/Getting_Started/Vitis/Part4-embedded_platform.md#targeting-hardware

The last v++ build command has "run_app.sh" as final argument - this is wrong name, the command fails, the correct name (from github sources) is run_hw.sh

This fix has been positive tested on my side

**Comment by randyh62** [comment]
Thanks for pointing out the issue. I will get it fixed.

**Comment by randyh62** [comment]
I have corrected the commands. Thanks for your input.
