### ISSUE TITLE
What should I do when I want the same buffer to be used for two different data types？

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#246]
I have two different data types: "ap_uint<8>" and "ap_fixed<16, 3, AP_RND, AP_SAT>", and I must open up just one buffer for the two different kinds of data in my design, how could I achieve it?
Thanks very much.

**Comment by imrickysu** [comment]
Hi @Candice-Yin , for general HLS questions, could you ask in Xilinx HLS Forum? Our technical support team will be happy to support you.
https://support.xilinx.com/s/topic/0TO2E000000YKXtWAO/hls?language=en_US 

This issue board is mainly for reporting tutorial issues.

cc @randyh62

**Comment by Candice-Yin** [comment]
OK，thank you @imrickysu

**Comment by Candice-Yin** [comment]
![fcb112ccb0316db7e8a7df7b0601688](https://user-images.githubusercontent.com/71826731/169549524-8bd2552d-6faf-4e17-9a3e-55b9591e901b.png)
I can‘t login the support community, do you know why?
Thank you. @imrickysu

**Comment by imrickysu** [comment]
Hi @Candice-Yin , could you reach out to the support_community@xilinx.com email alias and provide the login username used when trying to sign into the community? They will help you with the account issues.
