### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by maik123456789** [Xilinx/Vitis-Tutorials#25]
I am doing the yolov4 tutorial. 

when I run the scripts gen_yolo_train_labels.sh I get this error. 

I changed the paths of the train and annotations as it says. any help?

**Comment by pedrombmachado** [comment]
That probably means that the path to the images/image name is wrong.That error is thrown by OpenCV when the image is not found.
