### ISSUE TITLE
Alveo u250 - [XRT] ERROR: failed to load xclbin: Invalid argument

### ISSUE THREAD

**Issue by arishsatheesan** [Xilinx/Vitis-Tutorials#252]
Hello, 

I am doing the example vector addition tutorial (https://github.com/Xilinx/Vitis-Tutorials/tree/2022.1/Getting_Started/Vitis/Part4-data_center.md) and I am encountering this issue while trying the run on hardware. The bitstream generation was successful and when I try to run ./app.exe it throws this error. 
sw_emu and haw_emu are running well.

![image](https://user-images.githubusercontent.com/38071757/170708622-1818e29f-78f0-4fb8-b8c2-2b24a9492e74.png)

Best regards

**Comment by randyh62** [comment]
Can you provide a little more information about your shell and OS? Which U250 platform are you targeting? Which OS are you running on? Which version of the tools are you using?

**Comment by arishsatheesan** [comment]
Hello,

The screenshot shows the details. I am using Vitis 2022.1.

![image](https://user-images.githubusercontent.com/38071757/170729126-79fa3b6e-9543-4fce-80e3-541702690d92.png)
![image](https://user-images.githubusercontent.com/38071757/170729323-aa08250e-5a31-49a2-8229-1f1ded9d8cba.png)

**Comment by randyh62** [comment]
I am seeing a problem as well. Let me look into it further and get back to you. 

Best Regards,
Randy

**Comment by arishsatheesan** [comment]
Thank you!

**Comment by arishsatheesan** [comment]
Hello,

Some more information, if it helps.

![image](https://user-images.githubusercontent.com/38071757/170954674-5e26db62-1e2e-4e4d-9622-59c84dbbfe6b.png)

**Comment by arishsatheesan** [comment]
The issue is solved! The issue was with the shell partition. 

Another thread gives the required info: https://github.com/Xilinx/Vitis-Tutorials/issues/106

You can do a proper validation with the command: "/opt/xilinx/xrt/bin/xbutil validate --device 0000:d8:00.1 --verbose"

Some more info on fixing some of the errors here: https://xilinx.github.io/Alveo-Cards/master/debugging/build/html/docs/card-validation.html

Thanks!
