### ISSUE TITLE
XRT Error: No Device Found

### ISSUE THREAD

**Issue by nrllhclb** [Xilinx/Vitis-Tutorials#262]
Hello everyone,

I followed steps which is example of vitis-ai for zcu104, however all steps passed until putting the sdcard to the board.

In **version 2020.2** https://github.com/Xilinx/Vitis-Tutorials/blob/2020.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step4.md, 

When the step 2 of test 2 have been run the code as `./vadd binary_container_1.xclbin`, i would get following error on board interface console

```
[XRT] ERROR: No device found
Error: Unable to find Target Device [XRT] ERROR: device is nullptr
```

thanks for answer

**Comment by nrllhclb** [comment]
In addition, i have been getting the fail such as "Failed to init entropy source hwrng" during boot.

**Comment by sven2314** [comment]
Hi, @nrllhclb 
From my experience,  this kind of error "`[XRT] ERROR: No device found Error: Unable to find Target Device [XRT] ERROR: device is nullptr`"  may be caused of lacking ZOCL node which is a device tree node to be used to bind the ZOCL driver. Without this driver, XRT can not communicate with the PL side IPs. As a result that kind of error would occur.  So please convert your system.dtb file to system.dts file to check whether it has the ZOCL node or not.  If there is no ZOCL node  please refer to [step2](https://github.com/Xilinx/Vitis-Tutorials/blob/2020.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step2.md) to update the DTS file.

**Comment by AnusheelXilinx** [comment]
Closing the thread as there are no open concerns.

Thanks
Anusheel
