### ISSUE TITLE
apt-get command not found

### ISSUE THREAD

**Issue by mavoyang** [Xilinx/Vitis-Tutorials#265]
I followed, 'Vitis Custom Embedded Platform Creation Example on ZCU104', this tutorial to creat a platform for zcu106. I successfully ran vadd application and DPU AI demo on it, but i found the pelalinux can not find apt and apt-get command.  How can I fix this?

**Comment by imrickysu** [comment]
Hi @mavoyang , in PetaLinux rootfs, `dnf` is the default package management system. It can replace apt commands. Please refer UG1144 for more details.

**Comment by mavoyang** [comment]
Many thanks @imrickysu
