### ISSUE TITLE
HwAcc/F/09-Ethernet-Alveo: Unable to generate bitstream for Ethernet core alveo u250

### ISSUE THREAD

**Issue by arishsatheesan** [Xilinx/Vitis-Tutorials#270]
Hi,

I am trying to run the tutorial https://github.com/Xilinx/Vitis-Tutorials/tree/2022.1/Hardware_Acceleration/Feature_Tutorials/09-using-ethernet-on-alveo with alveo u250. 

I have used the evaluation licenses given in https://www.xilinx.com/products/intellectual-property/ef-di-25gemac.html, but I am unable to generate the bitstream. The error states that the bitstream generation is not permitted for the core used. Which other license do I need for this tutorial? 

Best regards,

**Comment by imrickysu** [comment]
Hi @Rampagee , could you add license expectation to the tutorial? Thanks.

**Comment by Rampagee** [comment]
Sorry for late response. Generally, the following two license keys are needed:
xxv_eth_mac_pcs
x_eth_mac

Or refer to following link:
https://www.xilinx.com/products/intellectual-property/ef-di-25gemac/ef-di-25gemac-order.html

If the evaluation licenses are not working, please check the license status in Vivado license manager or consult the licensing solution center... Thanks.

**Comment by arishsatheesan** [comment]
> Sorry for late response. Generally, the following two license keys are needed: xxv_eth_mac_pcs x_eth_mac
> 
> Or refer to following link: https://www.xilinx.com/products/intellectual-property/ef-di-25gemac/ef-di-25gemac-order.html
> 
> If the evaluation licenses are not working, please check the license status in Vivado license manager or consult the licensing solution center... Thanks.

Thanks for the response.

Both of the above mentioned licences are installed, but still the bitstream generation is failing. 
![image](https://user-images.githubusercontent.com/38071757/187178378-b8469e9f-c058-496c-8777-0f5911b257d4.png)

**Comment by Rampagee** [comment]
Hi, @arishsatheesan, when you apply for the evaluation license from the Xilinx licensing site, you should add both following items, like the snapshot below:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/10832063/187358519-fc6309fd-552b-4f36-81b0-5560062dbb57.png">

After importing the generate license file, you should observe the license status in License Manager like below snapshot:
![image](https://user-images.githubusercontent.com/10832063/187358659-f40ec684-04d7-46ab-8cad-76209d6b43b8.png)

If this is not the case for you, maybe you need to redo the license generation and importing steps.

**Comment by arishsatheesan** [comment]
I generated the license as suggested and imported it. Still did not work.

![image](https://user-images.githubusercontent.com/38071757/187875757-c90e525f-1ddb-4a35-85b0-58ba47c7bb9b.png)

Could you please run and check it once to confirm it?

Thanks!

**Comment by Rampagee** [comment]
I've tried the license generation flow as mentioned above using a fresh new machine, and the flow can pass. When the generated license is imported with Vivado license manager, whether the following features are avaible in your machine?

![image](https://user-images.githubusercontent.com/10832063/188549463-bf9dd62c-01af-4b42-bbdb-776b357b2766.png)

**Comment by arishsatheesan** [comment]
Yes, I see all these features in my machine too.

![image](https://user-images.githubusercontent.com/38071757/188631713-2091ca71-dc8b-4db9-b9b2-c91aa3b0383d.png)

**Comment by AnusheelXilinx** [comment]
If there are any open queries, please feel free to post it in Install and Licensing Community Forums:
https://adaptivesupport.amd.com/s/topic/0TO2E000000YKXwWAO/installation-and-licensing?language=en_US

Thanks
Anusheel
