### ISSUE TITLE
Vitis_Platform_Creation-kv260 step3 Load the hardware sudo xmutil command 'xmutil' not found

### ISSUE THREAD

**Issue by chenguoping76** [Xilinx/Vitis-Tutorials#280]
Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/step3.md 

4.  Load the hardware 
    sudo xmutil listapps
    command 'xmutil' not found

![D}A7PM(R$(J5PON}G)VFW9L](https://user-images.githubusercontent.com/35511222/182349531-f226ae4a-b582-4d6d-8bd8-b6e4d8bf7f63.png)

**Comment by imrickysu** [comment]
Hi @chenguoping76 , xmutil is a special command only available in KV260 rootfs, which is prebuilt and write to SD card directly.
If you use the rootfs from common image, it doesn't include xmutil utility.

**Comment by sven2314** [comment]
@chenguoping76 Please follow the following link to update the sdcard Image which is official image for kv260 and contains the xmutil command.
[kv260-getting-started](https://www.xilinx.com/products/som/kria/kv260-vision-starter-kit/kv260-getting-started/getting-started.html)

**Comment by chenguoping76** [comment]
3ks，I got the difference. Kv260 has two prebuild system: ubuntu is a desktop; petalinux editor is hw acceleration platform.
