### ISSUE TITLE
For a vivado project that supported vitis extensible plaform, How to match xsa and xpfm ?

### ISSUE THREAD

**Issue by dreamella** [Xilinx/Vitis-Tutorials#282]
1 Vivado IDE create a project that supported vitis extensible plaform
2 petalinux create image
3 vitis IDE create a platform project in order to output xpfm file?  
4 while execute platform -p xxx.xpfm, find out xsa and xpfm dismatch.
How to match xsa and xpfm? 
![image](https://user-images.githubusercontent.com/81511317/182516932-ab87c6ac-36e8-43f7-ae3a-68ac885bdf72.png)
![image](https://user-images.githubusercontent.com/81511317/182517031-ed5822e7-9663-465b-bdc8-286cb91cc317.png)

**Comment by imrickysu** [comment]
Hi @dreamella , it looks like you're reporting a tool issue. If you can post this question in [forums.xilinx.com ](http://forums.xilinx.com/), with the source files to reproduce issue, AMD/Xilinx Technical Support team would help to investigate and verify whether this is a tool issue. If it is, they can report this bug to the Engineering team to fix this issue.

If you export your block design to tcl scripts, you can check whether there are any description of HPC1 in the tcl. I'm not sure whether it's possible that the setup of HPC1 is broken. It makes Platform Setup GUI thinks it's not a valid port to export, but the platform generation function still sees this port. BD tcl can tell more details.
