### ISSUE TITLE
AIE/D/07-firFilter: README contains incorrect path could be misleading

### ISSUE THREAD

**Issue by allyzhou** [Xilinx/Vitis-Tutorials#286]
https://github.com/Xilinx/Vitis-Tutorials/blob/2022.1/AI_Engine_Development/Design_Tutorials/07-firFilter_AIEvsHLS/AIE/README.md
Under "Building The Design" -> "Make Steps" To run the following make steps (e.g. make kernels, make graph, etc), you must be in the Makefiles/ folder.
`cd Makefiles` 
But the Makefiles folder does not exist, please update the README.md

**Comment by imrickysu** [comment]
Hi @JithinPillai , do you mean the folder contains the `makefile` ?

**Comment by AnusheelXilinx** [comment]
@allyzhou, I do not see any makefile folder. Closing, as this looks fixed. 

Thanks
Anusheel
