### ISSUE TITLE
Modify DPU type (3136, 4096 and so on) for KV260

### ISSUE THREAD

**Issue by vaan2010** [Xilinx/Vitis-Tutorials#288]
Hi,
I want to use KV260 for some custom applications, and I find various DPU types in KV260 such like 1024, 3136, 4096 and so on.
The models from Vitis AI github are compiled with DPU 4096, But my KV260 is DPU 3136.
So I want to modify the DPU type from 3136 to 4096 through Vivado, and another problem show up: KV260 has no DPU IP in Vivado!

Does anyone could give me some suggestions or Xilinx tutorial for build different DPU type for KV260?

Thanks,
Norris

**Comment by allyzhou** [comment]
Please contact https://github.com/Xilinx/Vitis-AI
