### ISSUE TITLE
ZCU106 cannot boot from SD card(ZCU106-Vitis-Platform-Creation-step4-DPU-example) 

### ISSUE THREAD

**Issue by HankIC** [Xilinx/Vitis-Tutorials#296]
Hello, I follow the tutorials (https://github.com/Xilinx/Vitis-Tutorials/tree/2021.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104) and change board information from ZCU104 to ZCU106 in step1 and step2 and step3. However, when I test the platform in step4(test vadd), I cannot get correct output and don't know how to debug this problem. Could any friends give me some advice？ Thank you very much!
scrpits here:(have to change the path of sstate cache in step2 and Vitis version is 2021.2)
[scripts.zip](https://github.com/Xilinx/Vitis-Tutorials/files/9453851/scripts.zip)
![error1](https://user-images.githubusercontent.com/110684722/187466781-d720e40f-7bf3-4d20-baa5-44d29a8c137e.png)
![error2](https://user-images.githubusercontent.com/110684722/187466789-34d94ed5-4179-46b8-bd72-8cd7123706ec.jpg)

**Comment by HankIC** [comment]
New update: I use official **ZCU104** [image](https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-zcu104-dpu-v2021.1-v1.4.0.img.gz) and boot it in **ZCU106**. I get the same output. Maybe some unknown configurations other than board name and information should be changed in scripts.

I plan to follow the readme file step by step and update the result here
![error3](https://user-images.githubusercontent.com/110684722/187612740-8a903c27-8f77-40e2-af59-1999bffe8229.png)

**Comment by HankIC** [comment]
In the step2, I find zcu106 dts is different from zcu104 according to [link](https://lore.kernel.org/all/CAHTX3dKFBiGpkK0XcWacArxA7KGxrYj_L1BpFyRzwmGP36e-sA@mail.gmail.com/T/#Z2e.:..:e29ef27a6a3bd52784b5e59f20d8b7f9b02a8e9d.1578396789.git.michal.simek::40xilinx.com:1arch:arm:dts:zynqmp-zcu106-revA.dts). I try to change it and update the result later


update: I change the system usr dts file 
&sdhci1 {
	status = "okay";
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_sdhci1_default>;
	xlnx,mio-bank = <1>;
};
and follow the read me file step by step and It works! There must be some errors in my scripts and I will try to correct them and I don't know whether I make a precise modification to the mentioned dts file or not.
![pass](https://user-images.githubusercontent.com/110684722/187901224-63023b26-7edb-443f-a753-ba86b207d064.jpg)

**Comment by HankIC** [comment]
New update: Vadd example can run, but DPU example can't work and ZCU106 cannot boot from SD card again. I don't know how to fix this issue now.
In the step1 clock frequencies:100 200 400, but in step4 dpu example clock freqs are set to 300 and 600?! should I change? 
![error_dpu](https://user-images.githubusercontent.com/110684722/188084727-35f7a327-4bf4-40b9-9b80-ed174c100f1f.png)

**Comment by HankIC** [comment]
New update: It can't work at the first time, but when I try to boot from SD card for the third time, It can work!!!!!
I wonder why my project is so unstable?????

**Comment by sven2314** [comment]
@HankIC Hi Hank, 
Please check  this link: https://github.com/Xilinx/Vitis-Tutorials/issues/287 to update the TCL file to support zcu106 and enable the I2C0 support.
When you build the PeTalinux project in step2 please change the machine name to "zcu106-reva". Then it will automatically add the zcu106 board level dtsi file. That means you will not need to modify the DTS file manually.

**Comment by AnusheelXilinx** [comment]
Resolution was provided in the last post. Closing as there are no further queries.

Thanks
Anusheel
