### ISSUE TITLE
Unable to choose a platform. "platform 'xilinx_u250_gen3x16_xdma_4_1_202210_1' (version 2022.1) is not supported by the current tool version (.)"

### ISSUE THREAD

**Issue by arishsatheesan** [Xilinx/Vitis-Tutorials#298]
Hi, 

I was trying to create a new application project in vitis and I encountered this issue. I never had this issue before while creating an application project with the same platform and same Vitis version. 

"Platform 'xilinx_u250_gen3x16_xdma_4_1_202210_1' (version 2022.1) is not supported by the current tool version (.). By policy, the platform version can not be newer than the current tool version"

![image](https://user-images.githubusercontent.com/38071757/188631008-bae19b99-ae70-4029-8f51-8e386fe09679.png)

Any idea why am I getting this error?

Thanks!

**Comment by randyh62** [comment]
Maybe it has to do with the version of XRT you have installed? Can you post the build versions of the Vitis tools and XRT?

**Comment by imrickysu** [comment]
Closing this issue due to no response from reporter. Please reopen if you encounter the same issue or can provide more info.
