### ISSUE TITLE
Running HW/F/09-Ethernet on Alveo U25

### ISSUE THREAD

**Issue by erenkal** [Xilinx/Vitis-Tutorials#306]
Hello,
I need to run this Ethernet Example on alveo u25 but it is not predefined in Makefile. 
Where can I find GT Clock speeds etc. to configurate it manually ?
Is there anything else I need ?
Thanks

**Comment by Rampagee** [comment]
Hi, @erenkal, U25 is a Smart NIC specific card, instead of a general Alveo accelerator card, the platform is not open to public for download yet, and please contact your local sales/FAE for Vitis platform and other necessary files (such as Vivado board file, etc.). Thanks.
