### ISSUE TITLE
Could I use <ap_fixed.h> in the host.cpp?

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#307]
![image](https://user-images.githubusercontent.com/71826731/193828360-9e889089-e180-492e-bd5e-324230755199.png)
I create buffers for fixed-point arrays in the host file.
How can I solve this question?

**Comment by imrickysu** [comment]
Hi @Candice-Yin , this looks like a generic HLS question. Could you ask this question in Xilinx forms? https://forums.xilinx.com/
It has an [HLS topic](https://support.xilinx.com/s/topic/0TO2E000000YKXtWAO/hls?language=en_US). Vitis HLS engineers will support you there.
