### ISSUE TITLE
The document you are looking for has been moved or deleted

### ISSUE THREAD

**Issue by zyt1024** [Xilinx/Vitis-Tutorials#313]
when I tried to click  ”For more information, refer to [Enabling the Vitis Kernel Flow](https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Vitis-HLS-Process-Overview) in the Vitis HLS Flow of the Vitis Unified Software Platform Documentation (UG1416)“. the link will tell me this message `The document you are looking for has been moved or deleted`.[
![image](https://user-images.githubusercontent.com/42999008/199925950-0b8d34dd-e01a-4c87-be87-6b82b715b589.png)
](url)

**Comment by imrickysu** [comment]
Hi @zyt1024 , pleas visit https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Vitis-HLS-Flow-Overview.
Thanks for reporting this issue. We will update the doc accordingly.

**Comment by imrickysu** [comment]
Hi @randyh62 , there are many places referred to this chapter. Could you help to confirm and update? Thanks.
https://github.com/Xilinx/Vitis-Tutorials/search?q=Enabling+the+Vitis+Kernel+Flow

**Comment by zyt1024** [comment]
> Hi @zyt1024 , pleas visit https://docs.xilinx.com/r/en-US/ug1399-vitis-hls/Vitis-HLS-Flow-Overview. Thanks for reporting this issue. We will update the doc accordingly.
Thanks

**Comment by randyh62** [comment]
I will fix this. Thanks.

**Comment by randyh62** [comment]
This has been promoted and should be fixed in a few days. I will mark this issue closed. Thanks for bringing it to our attention.
