### ISSUE TITLE
ERROR when build xo /03-rtl_stream_kernel_integration

### ISSUE THREAD

**Issue by ykgot** [Xilinx/Vitis-Tutorials#32]
When I tried to build xo with the following comment for 03-rtl_stream_kernel_integration project, it had some ERRORs.
How to solve this?
Thanks!

make all_xo TARGET=hw PLATFORM=xilinx_u200_xdma_201830_2

ERROR: [v++ 214-160] in function 'alpha_mix': Local stream 'mixed_img.4' has conflict depth setting (xx/03-rtl_stream_kernel_integration/hw/alpha_mix.cpp:46:61)
ERROR: [v++ 214-160] in function 'alpha_mix': Local stream 'resized_time_img.4' has conflict depth setting (xx/03-rtl_stream_kernel_integration/hw/alpha_mix.cpp:44:61)

**Comment by fmanuelsg** [comment]
same issue on a working project build with 2020.1

**Comment by rwarmstr** [comment]
These tutorials have this issue if you run 2020.1 tutorials on 2020.2 with Vitis HLS, the repos have since been updated. Please let us know if you still see this.

**Comment by manuel-sanchez-nttdisruption** [comment]
2020.2

**Comment by rwarmstr** [comment]
You'll see the issue if you build the 2020.1 tutorial branch on 2020.2. You should not see the issue if you build the 2020.2 branch on 2020.2. We also committed a patch yesterday against the 2020.1 branch that should resolve it, but please let us know if you continue to see difficulties.
