### ISSUE TITLE
omitting -hw_emu argument from platform create fails in Platform validation step with platforminfo 

### ISSUE THREAD

**Issue by marctylerb** [Xilinx/Vitis-Tutorials#320]
There is a note in step 2 that indicates the -hw_emu can be omitted, but doing so causes the step 3 platforminfo command to fail.

_Note: If you don't need to support hardware emulation, you can omit the option -hw_emu and its value for the command platform create._

First, it appears there is a typo, as the argument appears to be "-rp" with "hw_emu" sub-argument.

`# Create a platform project
platform create -name vck190_dfx_custom \
    -desc "A custom VCK190 DFX platform" \
    -hw <Static>.xsa \
    -rp {id 0 hw <RP>.xsa hw_emu <HW_EMU>.xsa} \
    -out <Output_Directory> \
    -no-boot-bsp 
`
Mainly, the step 3 platforminfo command fails when the platform has the hw_emu omitted, and the resulting .xpfm does not contain the hw_emu XSA.

`platforminfo -p    ./step2_sw/build/pfm/vck190_custom_dfx/export/vck190_custom_dfx/vck190_custom_dfx.xpfm
WARNING: [Common 17-259] Unknown Tcl command 'platforminfo -p ./step2_sw/build/pfm/vck190_custom_dfx/export/vck190_custom_dfx/vck190_custom_dfx.xpfm' sending command to the OS shell for execution. It is recommended to use 'exec' to send the command to the OS shell.
Error parsing platform file: /group/techsup/marcb/00297441/git_tut/Vitis-Tutorials-2022.1-validate/Vitis-Tutorials-2022.1/Vitis_Platform_Creation/Design_Tutorials/04_Edge_VCK190_DFX/ref_files/step2_sw/build/pfm/vck190_custom_dfx/export/vck190_custom_dfx/vck190_custom_dfx.xpfm
Line number:13. Mandatory element missing
Exception: failed to parse the XPFM file
xsct% child process exited abnormally`

**Comment by imrickysu** [comment]
Hi @marctylerb , thanks for reporting this issue.

In 2022.1, if you omit the hw_emu XSA, the generated platform cannot work properly for both platforminfo and v++ link. This issue should have been fixed in 2022.2. 

@sven2314  could you update the 2022.1 tutorial doc to clarify the known issue of `hw_emu` option requirement? Thanks.
