### ISSUE TITLE
Getting_Started/Vitis/Part4-data_center  software emulation fail

### ISSUE THREAD

**Issue by 2748669816** [Xilinx/Vitis-Tutorials#325]
When I followed the tutorial to the fourth part of the software simulation, I failed。
This step in the tutorial--

export XCL_EMULATION_MODE=sw_emu
./app.exe

The error returned looks like this--
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file './vadd.xclbin' for reading

I didn't find a solution.

**Comment by randyh62** [comment]
The vadd.xclbin is created during the link process:
v++ -l -t sw_emu --platform xilinx_u200_gen3x16_xdma_2_202110_1 --config ../../src/u200.cfg ./vadd.xo **-o ./vadd.xclbin**

When you run this command does the tool return any errors?

**Comment by randyh62** [comment]
As I have not heard back in a week I am closing the issue again. Feel free to reopen if necessary.
