### ISSUE TITLE
error occurs in Hardware Emulation

### ISSUE THREAD

**Issue by Root970103** [Xilinx/Vitis-Tutorials#345]
When using vitis for hardware emulation， an error occured. The infomation in log file is below.
![1672022019854](https://user-images.githubusercontent.com/44917879/209539226-de705e8e-e074-4804-adbb-22a297ca920d.png)

Does anyone know the reason for this error?

**Comment by Root970103** [comment]
Platform description

![1672022358178(1)](https://user-images.githubusercontent.com/44917879/209539580-71770a65-213d-4380-8da2-060ec220e85e.png)

**Comment by allyzhou** [comment]
Please contact your AMD Xilinx or Aliyun support channel, e.g. support center or forum. We only support tutorial-related issues or questions here. Thanks.
