### ISSUE TITLE
13-aie-performance-analysis: Facing runtime errors when I try to find the graph latency using 13-aie-performance-analysis

### ISSUE THREAD

**Issue by Hari-MathWorks** [Xilinx/Vitis-Tutorials#360]
**Describe the issue**
I was able to successfully run the "**13-aie-performance-analysis**" on both Hardware emulation and actual hardware with out any modifications. But If I use the `event::start_profiling(gr.in, gr.dataout, event::io_stream_start_difference_cycles)` to find the graph latency, then I was facing the issues.
Below is the screenshot of the modifications I made to the [host.cpp](https://github.com/Xilinx/Vitis-Tutorials/blob/2022.2/AI_Engine_Development/Feature_Tutorials/13-aie-performance-analysis/testcase_ssfifo/sw/host.cpp) file:
![image](https://user-images.githubusercontent.com/82861359/213436178-0f59c311-c381-4897-b535-2892a4d4f62f.png)

You can find the complete modified host.cpp file from below:
[host_modified.cpp.txt](https://github.com/Xilinx/Vitis-Tutorials/files/10456764/host_modified.cpp.txt)

**To Reproduce**
1. Modify the `Vitis-Tutorials/blob/2022.2/AI_Engine_Development/Feature_Tutorials/13-aie-performance-analysis/testcase_ssfifo/sw/host.cpp` file with modifications mentioned in above section.
2. Run the hardware emulation step mentioned in this [link](https://github.com/Xilinx/Vitis-Tutorials/blob/2022.2/AI_Engine_Development/Feature_Tutorials/13-aie-performance-analysis/aie_execution_measurement.md) i.e., `make run_hw_emu`.
3. In the emulator run `host.exe a.xclbin`
4. You will see below error:
![hwEmulationRunTimeError](https://user-images.githubusercontent.com/82861359/213446410-1f39896c-92c3-45a4-8eb4-88ef3a0d6874.png)

**Your environment: **
- OS: Ubuntu 22.04.1 LTS
- Software Version: 2022.2
- Hardware (if applicable): VCK190

**Comment by xflorentw** [comment]
Hi @Hari-MathWorks 

This question is not directly related to the tutorial. Do you mind opening a topic on the forums for this question:
https://support.xilinx.com/s/?language=en_US

Thanks

Florent

**Comment by xflorentw** [comment]
This question has been asked on the forums and technical support is investigating the issue:
https://support.xilinx.com/s/question/0D54U00006FZmseSAD/facing-runtime-errors-when-i-try-to-find-the-graph-latency-using-13aieperformanceanalysis-tutorial

**Comment by AnusheelXilinx** [comment]
Issue is fixed as per the forums discussion, closing the issue. 

Thanks
Anusheel
