### ISSUE TITLE
Cannot integrate the DPU Kernel (RTL Kernel) on a custom design

### ISSUE THREAD

**Issue by davendramaharaj1** [Xilinx/Vitis-Tutorials#361]
I am having an issue integrating the DPU into my Vitis project. I am following the procedure outlined in the README under DPUCZDX8G/prj/Vitis for Vitis 2.5. I extracted the DPUCZDX8G.tar.,gz file which created the DPUCZDX8G folder. Then I added it to Library Repositories as follows:

![image](https://user-images.githubusercontent.com/54917008/217406600-0f8aec83-58ab-4703-adaa-e1705e3977a9.png)

I tried creating an application project, selected my custom platform that I created (kv260_custom.xpfm). Then I set the following:

- sysroot path = <kv260_custom_pkg>/sysroot/cortexa72-cortexa53-xilinx-linux,
- rootfs path = kv260_custom_petalinux/xilinx-kv260-starterkit-2022.2/images/linux/rootfs.ext4
- kernel image path = kv260_custom_plnx/xilinx-kv260-starterkit-2022.2/images/linux/Image.

After this, I tried to select "DPU Kernel (RTL Kernel). Moreover, I cannot move on as "Finish" does not work as shown here:

![image](https://user-images.githubusercontent.com/54917008/217406635-512816c7-fa7e-4f29-b3f3-eb4834b77eba.png)

 
I am not sure what's supposed to happen here. The following are the system configurations:

- OS: Ubuntu 22.04
- Vitis: 2022.2
- Board: KV260
- DPU TRD from Vitis AI 2.5

**Comment by xflorentw** [comment]
Hi @davendramaharaj1 

This issue section is for issues related to tutorials which are part of this current Vitis-Tutorials repository.
You question is not about an issue of any of the tutorials present in this repository.

For general questions on the Vitis tools, please ask on the support community forums: https://support.xilinx.com/s/

**Comment by imrickysu** [comment]
Hi @sven2314 , if you have related experience, please share with @davendramaharaj1 .

Hi @davendramaharaj1 , checking with the community forums is recommended. We'll share our experiences when possible.

**Comment by davendramaharaj1** [comment]
Hi @imrickysu, I have also posted on the Xilinx forums under Vitis AI and Vitis Acceleration & Acceleration here: https://support.xilinx.com/s/question/0D54U00006MlYUnSAN/cannot-select-the-dpu-kernel-rtl-kernel-as-a-template?language=en_US

but no one has offered advice yet.

**Comment by sven2314** [comment]
@davendramaharaj1 
Hi,  I tried this method to add DPU kernel. When I create an application it can detect the DPU application.
![image](https://user-images.githubusercontent.com/94431691/217985599-4a91d9b8-809e-4d71-a3ed-91c5d4f4b64f.png)
Just click finish it can complete the project creation.
Vitis 2022.2
Ubuntu
VAI 2.5

**Comment by davendramaharaj1** [comment]
@sven2314 If you look at my first screenshot, I have already added the path to the DPU library I downloaded for Vitis 2.5. Then, I tried to repeat the steps you just posted after creating an application. If you look at the 2nd screenshot, I tried to add the DPU Kernel and the box to the right is blank. Also, I could not move on by clicking "Next".

**Comment by davendramaharaj1** [comment]
I see got it. For some reason, my vitis gui does not generate any info on the right text box so it's a bit weird. But I got the project creation working. Thanks anyway.
