### ISSUE TITLE
can't find xrt 2021.2 version

### ISSUE THREAD

**Issue by yangyazhou97** [Xilinx/Vitis-Tutorials#368]
I want to download and install xrt 2021.2 version, but I only can find xrt 2022.2 version, how can I find xrt 2021.2 version?
https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-platforms/2022-2.html
![image](https://user-images.githubusercontent.com/89854398/220227416-a6314c7d-379d-446b-a0fd-f4a63149e47b.png)

**Comment by imrickysu** [comment]
Hi @yangyazhou97 , to develop embedded acceleration applications, XRT on your host machine is not required before 2022.2. After 2022.2, XRT is only needed for software emulation.

**Comment by yangyazhou97** [comment]
Hi @imrickysu, thank you so much.
