### ISSUE TITLE
Checking timing violation path

### ISSUE THREAD

**Issue by m-kru** [Xilinx/Vitis-Tutorials#373]
I have received negative slack for my kernel. Is there any way to identify logic path causing the timing violation from the Vitis HLS GUI? I feel like I have gone though all reports, clicked all possible icons, but still no info on operations causing the timing violation.

**Comment by imrickysu** [comment]
Hi @randyh62 , could you help with this question?

Hi @m-kru , it's recommended to ask this generic question in the forums: http://forums.xilinx.com/

**Comment by m-kru** [comment]
@imrickysu The one that Xilinx wipes out once every few years, so that people cannot see how many bugs are in the Xilinx software?

**Comment by randyh62** [comment]
Which version are you working with?

**Comment by m-kru** [comment]
2021.2

**Comment by randyh62** [comment]
You can run Vivado Synthesis and Implementation to generate timing reports from Vitis HLS. You can do this from the Implementation menu in the Flow Navigator, or by using the **config_export** command and then running **export_design** in a Tcl script. 

I am attaching some screenshots from the 2021.2 release for your review. 

![implementation-dialog-box](https://user-images.githubusercontent.com/42045079/229580359-7e022c51-c535-4ebf-8419-ec242dabb7b9.png)
![vivado_synthesis-timing_reports](https://user-images.githubusercontent.com/42045079/229580362-e1bf1ed6-a565-49c4-9b8c-bf9855f6ebe4.png)

**Comment by AnusheelXilinx** [comment]
Closing as there are no further queries. 

Thanks
Anusheel
