### ISSUE TITLE
Vitis-Tutorials/Hardware_Acceleration/Feature_Tutorials/09-using-ethernet-on-alveo: Cannot generate bitstream for x4 Ethernet on U250

### ISSUE THREAD

**Issue by ash8327** [Xilinx/Vitis-Tutorials#377]
** Which tutorial are you running? **
Vitis-Tutorials/Hardware_Acceleration/Feature_Tutorials/09-using-ethernet-on-alveo.

** Describe the issue **
The x1 example works correctly but when changing the lanes to x4 the bitstream generation fails:

===>The following messages were generated while  Compiling (bitstream) accelerator binary: top_level_x4 Log file: /home/shammett/Storage/Vitis-Tutorials/Hardware_Acceleration/Feature_Tutorials/09-using-ethernet-on-alveo/_x/link/vivado/vpl/prj/prj.runs/impl_1/runme.log  :
ERROR: [VPL 17-69] Command failed: This design contains one or more cells for which bitstream generation is not permitted:
level0_i/level1/level1_i/ulp/eth0/inst/i_ethernet_0/inst/i_xxv_ethernet_x4_0_top_3/i_xxv_ethernet_x4_0_CORE (<encrypted cellview>)
level0_i/level1/level1_i/ulp/eth0/inst/i_ethernet_0/inst/i_xxv_ethernet_x4_0_top_2/i_xxv_ethernet_x4_0_CORE (<encrypted cellview>)
level0_i/level1/level1_i/ulp/eth0/inst/i_ethernet_0/inst/i_xxv_ethernet_x4_0_top_1/i_xxv_ethernet_x4_0_CORE (<encrypted cellview>)
If a new IP Core license was added, in order for the new license to be picked up, the current netlist needs to be updated by resetting and re-generating the IP output products before bitstream generation.

** To Reproduce **
Follow the instructions to change the lane from x1 to x4 in 09-using-ethernet-on-alveo
Set the card to the U250

** Your environment: **
- OS: Ubuntu 20.04
- Software Version:  2022.1
- Hardware: U250

** Additional context **
I have the temporary hardware license but when using it in Vivado I can successfully generate x4 25G Ethernet with it

**Comment by AnusheelXilinx** [comment]
Hi @ash8327, I was able to build the design with x4. The run was completed at my end. 
If there are any license queries, please post your query on our Installation and Licensing Forums:
https://adaptivesupport.amd.com/s/topic/0TO2E000000YKXwWAO/installation-and-licensing?language=en_US

Thanks
Anusheel
