### ISSUE TITLE
Get moving with Alveo: fails on sw_emu

### ISSUE THREAD

**Issue by bootonly** [Xilinx/Vitis-Tutorials#381]
** Which tutorial are you running? **
https://github.com/Xilinx/Vitis-Tutorials/tree/2022.2/Hardware_Acceleration/Design_Tutorials/10-get_moving_with_alveo

** Describe the issue **
It fails on sw_emu.

** To Reproduce **
Type: make run TARGET=sw_emu and it will report the error: terminate called after throwing an instance of 'std::runtime_error'
  what():  Multiple instances of XRT core shim library detected, only one
can be loaded at any given time.  Please check if application is
explicity linked with XRT core library (xrt_core, xrt_hwemu, or
xrt_swemu) and remove this linking. Use XCL_EMULATION_MODE set to
either hw_emu or sw_emu if running in emulation mode.
/bin/sh: line 1: 470683 Aborted                 (core dumped) XCL_EMULATION_MODE=sw_emu ./00_load_kernels alveo_example.xclbin
make: *** [Makefile:26: run] Error 134

** Screenshots **
![image](https://user-images.githubusercontent.com/41948166/232947599-4670c0a4-6dac-4974-ba7c-cca42f1fa110.png)

** Your environment: **
- OS: 22.04
- Software Version: 2022.2
- Hardware (if applicable): u250

** Additional context **

**Comment by AnusheelXilinx** [comment]
Hi bootonly, 

Please ensure the build was also run with TARGET=sw_emu as the correct libraries are needed. 
If the build was done with TARGET=sw_emu and you are still seeing the issue, can you please try to modify "design_source/cmake/Modules/FindXRT.cmake" as below and let me know if it works:

From: set(XRT_LIBS ${LIBXRT_CORE_LIBRARY} ${LIBXRT_XILOCL_LIBRARY})
to: set(XRT_LIBS ${LIBXRT_XILOCL_LIBRARY})

**Comment by AnusheelXilinx** [comment]
Closing as there are no further queries. 

Thanks
Anusheel
