### ISSUE TITLE
guided_software_examples.md  missing dir under Hardware_Acceleration

### ISSUE THREAD

**Issue by InspireSemi** [Xilinx/Vitis-Tutorials#395]
I am trying to build the example for the U250. 
I could not find this dir : Hardware_Acceleration/Introduction/design_src/hw_src

I did find some source under : Vitis-Tutorials/Hardware_Acceleration/Design_Tutorials/10-get_moving_with_alveo/design_source/hw_src
I changed the config.mk to match the U250
PLATFORM ?= xilinx_u250_gen3x16_xdma_4_1_202210_1

It starts to build but errors out missing a header file:  common/xf_common.hpp

What steps/repo/dir am I missing?

**Comment by InspireSemi** [comment]
Created a dir under 10-get_moving_with_alveo/design_source/hw_src/  called common,
Found the headers under 03-rtl_stream_kernel_integration/hw/include/common
Copied the *.hpp from here to the new dir this still failed but with a different error.  An undefined variable?

Moved the headers from 10-get_moving_with_alveo/design_source/hw_src/common to 10-get_moving_with_alveo/design_source/hw_src/  and this now compiles.
I see the same headers under Vitis_Libraries/.../include/common/  with one exception. 
xf_axi_sdata.hpp is not in this path but in the files i copied over from 03-rtl_stream_kernel_integration/

Build line from compile:
v++ --kernel resize_accel_rgb --platform xilinx_u250_gen3x16_xdma_4_1_202210_1 -t hw -s -g -I. -I./Vitis_Libraries/vision/L1/include --config vision_config.ini -c -o resize_rgb.xo resize_rgb.cpp

**Comment by imrickysu** [comment]
Hi @AnusheelXilinx , could you check this header file issue?

**Comment by InspireSemi** [comment]
I am not sure what changed but I removed all the header files that I copied over from 03-rtl_stream and it compiles ok. ??
