### ISSUE TITLE
README file for the AXIS External Traffic Generator Feature Tutorial is incorrect in 2023.1

### ISSUE THREAD

**Issue by xflorentw** [Xilinx/Vitis-Tutorials#401]
The README file is the main README file for the AI Engine development - features tutorials

**Comment by AnusheelXilinx** [comment]
Hi @xflorentw, with 2024.2 branch I see the correct readme: https://github.com/Xilinx/Vitis-Tutorials/blob/2024.2/AI_Engine_Development/AIE/Feature_Tutorials/16-external-traffic-generator-aie/README.md

Please let me know if you still see this issue. 

Thanks
Anusheel
