### ISSUE TITLE
How to package img file for VCK190 

### ISSUE THREAD

**Issue by bjwtsh** [Xilinx/Vitis-Tutorials#402]
** Which tutorial are you running? **
https://github.com/Xilinx/Vitis-Tutorials/tree/2023.1/AI_Engine_Development/Feature_Tutorials/05-AI-engine-versal-integration

** Describe the issue **
I want to learn how to package the img file for VCK190, so I try the 05 tutorials. But after I finish the package command: 
`make package TARGET=hw`
I can't find sd_card.img in sw folder. what the folder is
 <img width="260" alt="sw folder" src="https://github.com/Xilinx/Vitis-Tutorials/assets/40317880/2dafb003-bff7-4748-8774-c94db6dd8ab5">

** To Reproduce **
Because my g++ version is 4.8.5 ,I can't build host.exe with `make host`. I enter commands manually.
```
make xsa TARGET=hw
cd sw
g++ -Wall -c -std=c++1y  -I$(sysroots)/aarch64-xilinx-linux/usr/include/xrt  -o host.o host.cpp
g++ -L $(XILINX_XRT)/lib/ -lxrt_coreutil   -std=c++1y -o host.exe host.o
cd ..
make package TARGET=hw
```

** Your environment: **

- OS: CentOS Linux 7
- g++: 4.8.5
- vitis 2023.1
- platform: xilinx_vck190_base_202310_1

**Comment by imrickysu** [comment]
Hi @bjwtsh , could you take a look at v++_package.log and check whether there are any error messages?
It's possible that the v++ package step is interrupted due to missing 3rd party software packages.
