### ISSUE TITLE
bug report - one line need to be changed  in 10-GeMM_AIEvsDSP 

### ISSUE THREAD

**Issue by ChengyueWang** [Xilinx/Vitis-Tutorials#424]
Hi AIE team, 

I am writing to remind that 

https://github.com/Xilinx/Vitis-Tutorials/blob/7fd526ab65668ef3fec9b8090145a0dfcd76c2ce/AI_Engine_Development/AIE/Design_Tutorials/10-GeMM_AIEvsDSP/AIE/design/aie_src/graph.h#L112

this line
 adf::connect<>(mmult[i].out, matC_out[i].in[0]);

need to be changed as 
 adf::connect<>(mmult[i].out[0], matC_out[i].in[0]);

to make the program runnable

**Comment by imrickysu** [comment]
Hi @ChengyueWang , thanks for pointing out this issue. I've forwarded this message to the author.
