### ISSUE TITLE
Hardware Emulation Fails 2023.2 01-AIE-ML-programming-and-optimization

### ISSUE THREAD

**Issue by Joel-De** [Xilinx/Vitis-Tutorials#429]
When following along with the [tutorial](https://github.com/Xilinx/Vitis-Tutorials/blob/2023.2/AI_Engine_Development/AIE-ML/Design_Tutorials/01-AIE-ML-programming-and-optimization/README.md) hardware emulation is failing with the following output.

INFO: [aiecompiler 77-3379] Extracted physical device part from platform is : xcve2802-vsvh1760-2MP-e-S-es1 
INFO: [aiecompiler 77-749] Reading logical device VC2802.json
INFO: [aiecompiler 77-750] Reading physical device xcve2802-vsvh1760-2MP-e-S-es1
INFO: [aiecompiler 77-951] ###Start:Loading Device Part xcve2802-vsvh1760-2MP-e-S-es1
ERROR: [aiecompiler 77-45067] Could not load Device Part xcve2802-vsvh1760-2MP-e-S-es1
INFO: [aiecompiler 77-44881] Run completed. Find additional information in:

I would appreciate some guidance on whether this is an issue with my setup or an error with the tutorial. I'm able to run x86 sim and pass the provided matrix equivalence check, but both hw_emu and aiesim fail.

**Comment by xflorentw** [comment]
Answered in following topic:
https://support.xilinx.com/s/question/0D54U00007uw9WXSAY/hardware-emulation-fails-20232-01aiemlprogrammingandoptimization

Note: The tutorial is only expected to run in x86 simulation and AI Engine simulation.
HW emulation would require a valid license for es devices
