### ISSUE TITLE
JRE version is not right

### ISSUE THREAD

**Issue by MarchSakura** [Xilinx/Vitis-Tutorials#43]
When I use make to compile the *sw_emu* example, terminal displayed a warning ```Vitis/2020.2/tps/lnx64/jre9.0.4 does not exist```. But my jre version is 11.0.2. 
How to set JRE version correctly? 
I've tried set the ```RDI_JAVAROOT``` environment value.

**Comment by rwarmstr** [comment]
Hi @MarchSakura, it sounds like you probably have a larger installation issue, can you please post on the Xilinx forums for support? We aren't able to debug Vivado installation issues here. When you post please add information on your install OS, environment, etc.

Thanks!

https://forums.xilinx.com/t5/Installation-and-Licensing/bd-p/INSTALLBD
