### ISSUE TITLE
Tutorial "07-AI-Engine-Floating-Point" requires a fix

### ISSUE THREAD

**Issue by L30nardoSV** [Xilinx/Vitis-Tutorials#430]
Hi

https://github.com/Xilinx/Vitis-Tutorials/tree/2023.2/AI_Engine_Development/AIE/Feature_Tutorials/07-AI-Engine-Floating-Point#fpneg_mul

and

https://github.com/Xilinx/Vitis-Tutorials/tree/2023.2/AI_Engine_Development/AIE/Feature_Tutorials/07-AI-Engine-Floating-Point#fpneg_abs_mul

Present the same function signature, description, and code example, which is not expected as far as I understand.

**Comment by OTremois** [comment]
I corrected the README file

**Comment by AnusheelXilinx** [comment]
Thank you @L30nardoSV for reporting and @OTremois for fixing this issue. 

Thanks
Anusheel
