### ISSUE TITLE
Seeking tutorial on puning custom PyTorch Neural Network Vitis AI 2.5

### ISSUE THREAD

**Issue by stavros-p** [Xilinx/Vitis-Tutorials#436]
I'm struggling to find documentation and tutorials for using Vitis 2.5 AI Optimizer to prune custom PyTorch neural networks. Despite searching through official documentation and GitHub tutorials, I haven't found resources specifically addressing this need.

If there are any tutorials available that I might have overlooked, I would greatly appreciate guidance on where to find them.

**Comment by AnusheelXilinx** [comment]
@stavros-p, please feel free to post your query on Vitis AI to below forum:
https://adaptivesupport.amd.com/s/topic/0TO2E000000YKY9WAO/vitis-ai-ai?language=en_US

Thanks
Anusheel
