### ISSUE TITLE
Hardware_Acceleration/Design_Tutorials/06-cholesky-accel 

### ISSUE THREAD

**Issue by htprofessor** [Xilinx/Vitis-Tutorials#444]
Excuse me
this cholesky algorithm can solve the matrix of 512,what should I do to solve larger matrix like 1024 or more.
I changed MAXN and NCU ,but it doesnt work.
![image](https://github.com/Xilinx/Vitis-Tutorials/assets/103341765/da981034-6e37-4dac-9063-d44f9e0913be)
![image](https://github.com/Xilinx/Vitis-Tutorials/assets/103341765/6e1f8352-96e3-4dad-a991-eb1954fcaac3)

**Comment by allyzhou** [comment]
Hi @AnusheelXilinx  can you take a look at this issue. thanks

**Comment by AnusheelXilinx** [comment]
@htprofessor, If I run the "make TARGET=sw_emu run" after changing the "MAXN" and "NCU", I do not see any issues.

Thanks
Anusheel

**Comment by AnusheelXilinx** [comment]
Closing the issue as there are no further concerns. 

Thanks
Anusheel
