### ISSUE TITLE
Issues in Vitis-Tutorials/AI_Engine_Development/AIE/Feature_Tutorials /08-dsp-library

### ISSUE THREAD

**Issue by micmckay** [Xilinx/Vitis-Tutorials#445]
Issue #1: Under the "Compile the application" it references $DSPLIB_ROOT but does not inform the reader where this directory is or what the variable should be set too:

 

Add DSP include files location #########

DSP_FLAGS := --include=$(DSPLIB_ROOT)/L1/src/aie

DSP_FLAGS += --include=$(DSPLIB_ROOT)/L1/include/aie

DSP_FLAGS += --include=$(DSPLIB_ROOT)/L2/include/aie

 

Issue #2: Under the "Tutorial Overview" section, it says the design is a "decimation filter", but from my understanding, this is not a decimation filter design as the filter is not down-sampling

**Comment by allyzhou** [comment]
Thanks for reporting the issue, the owner has been notified and currently working on that.

**Comment by allyzhou** [comment]
fixed by d9bfb84681e73933b8f4fe699ff474af986d095b
