### ISSUE TITLE
Issue in AI_Engine_Development/AIE/Feature_Tutorials/16-external-traffic-generator-aie/SW-HW_Emulation

### ISSUE THREAD

**Issue by qingqins** [Xilinx/Vitis-Tutorials#446]
There are two 'syn.cflags' defined in below two cfg files.
HLS synthesis will fail with error "ERROR: [HLS 200-1923] Found duplicate ini entry [hls] syn.cflags"

https://github.com/Xilinx/Vitis-Tutorials/blob/2024.1/AI_Engine_Development/AIE/Feature_Tutorials/16-external-traffic-generator-aie/SW-HW_Emulation/pl_kernels/s2mm.cfg

https://github.com/Xilinx/Vitis-Tutorials/blob/2024.1/AI_Engine_Development/AIE/Feature_Tutorials/16-external-traffic-generator-aie/SW-HW_Emulation/pl_kernels/mm2s.cfg

**Comment by allyzhou** [comment]
Thanks for reporting the issue, the owner has been notified and currently working on that.

**Comment by allyzhou** [comment]
The error has been fixed via the commit 679390bfa60503b009c048d5e618445c55ad8f84
