### ISSUE TITLE
Missing image in Getting_Started/Vitis/Part4-embedded_platform.md

### ISSUE THREAD

**Issue by xilinx-nkrueger** [Xilinx/Vitis-Tutorials#449]
https://github.com/Xilinx/Vitis-Tutorials/blob/58e54fa809d6cdb4a59212055aa1d23e051f7ec7/Getting_Started/Vitis/Part4-embedded_platform.md?plain=1#L18

The image link from this tutorial is broken.

**Comment by imrickysu** [comment]
This is a public image in UG1393
Image: https://docs.amd.com/viewer/attachment/2AHmluw_4m~0LHemYekb6A/KyHSdLDPWS_frtia6T0YuA
Parent chapter: https://docs.amd.com/r/en-US/ug1393-vitis-application-acceleration/Introduction-to-the-Vitis-Unified-IDE

@xilinx-nkrueger Thanks for reporting this issue.
@sven2314  Please update the image link.

**Comment by xilinx-nkrueger** [comment]
Interesting... If paste the image URL into the browser the image loads up, but if I go to the readme, I see this:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/c793af80-6c68-468a-b201-687f4893947c">

And if I click the link, I see this:

<img width="448" alt="image" src="https://github.com/user-attachments/assets/4d223035-064d-43f3-8447-04b2511b5f2d">

I'm on the AMD VPN.

**Comment by AnusheelXilinx** [comment]
I can see the correct image with URL corrected to github.com. Closing the issue.
