### ISSUE TITLE
Data Transfer Between HBM and DDR

### ISSUE THREAD

**Issue by XiaojuWang** [Xilinx/Vitis-Tutorials#450]
The tutorial contains the examples that transfer data from HBM/DDR to the kernel. However, is there any methods or usable configurations that allow us to transfer data between HBM and DDR? Or should I manually add  a data transfer kernel dedicated to transfer data between HBM and DDR.

**Comment by imrickysu** [comment]
Hi @XiaojuWang , could you share some use case details for moving data between DDR and HBM? They are both memory storage resources. Purely moving data between them doesn't help much so it's not commonly used. 
If you'd like to move data between them, you can create a data mover kernel between them.
