### ISSUE TITLE
Bad link to Vitis Platform documentation

### ISSUE THREAD

**Issue by xilinx-nkrueger** [Xilinx/Vitis-Tutorials#452]
https://github.com/Xilinx/Vitis-Tutorials/blob/58e54fa809d6cdb4a59212055aa1d23e051f7ec7/Vitis_Platform_Creation/Design_Tutorials/03_Edge_VCK190/README.md?plain=1#L28

The link to: https://docs.amd.com/r/en-US/Vitis-Tutorials-Getting-Started/Vitis-Platform is invalid.

**Comment by imrickysu** [comment]
Hi @xilinx-nkrueger , this link is valid to me. Could you please confirm?

https://docs.amd.com/r/en-US/Vitis-Tutorials-Getting-Started/Vitis-Platform
![image](https://github.com/user-attachments/assets/0bb203f1-841a-4a4f-99cf-5e4db3fdad01)
