### ISSUE TITLE
Wrong value for PLATFORM_REPO_PATHS in 15 README.md files

### ISSUE THREAD

**Issue by ThomasGmeinder** [Xilinx/Vitis-Tutorials#458]
There are 15 README.md files which suggest this:
Set up your `PLATFORM_REPO_PATHS` environment variable to `$XILINX_VITIS/lin64/Vitis/2024.1/base_platforms/`.

The value  `$XILINX_VITIS/lin64/Vitis/2024.1/base_platforms/` is wronge in Vitis 2024.1. 

The correct path is:
`$XILINX_VITIS/base_platforms/`

**Comment by xflorentw** [comment]
I believe it is not even required to set PLATFORM_REPO_PATHS to $XILINX_VITIS/base_platforms/.
Vitis will check into $XILINX_VITIS/base_platforms/ in any case but the makefiles have to be modified to point to the platform name and not to the .xpfm file
