### ISSUE TITLE
Vitis Unified 2024 ide cannot create Platform Project

### ISSUE THREAD

**Issue by kenkit** [Xilinx/Vitis-Tutorials#464]
Hi, I have created and exported the xsa with vivado, now upon oppening the project with vitis I cannot create anything as the options are not there.
Basically I'm trying to do is create a vitis project from vivado as shown in this article 
https://wiki.trenz-electronic.de/display/PD/Vitis

**Comment by AnusheelXilinx** [comment]
Hi @kenkit, As the query not related to the tutorials, I request you to please post the query on Vitis Forums:
https://adaptivesupport.amd.com/s/topic/0TO2E000000YKXhWAO/vitis?language=en_US

Thanks
Anusheel
