### ISSUE TITLE
Are there a specific tutorial for a pytorch detection model?

### ISSUE THREAD

**Issue by daniperfer** [Xilinx/Vitis-Tutorials#48]
Hello,

I was able to successfully quantize and compile a pytorch classification network by following the instructions of the "[PyTorch flow for Vitis AI Tutorial](https://github.com/Xilinx/Vitis-Tutorials/blob/master/Machine_Learning/Design_Tutorials/09-mnist_pyt-master/README.md)" and the "Vitis AI [User Guide](https://www.xilinx.com/html_docs/vitis_ai/1_3/pytorch.html#nvh1592318322520)". These were my first steps with Vitis-AI. 

Now, my goal is to quantize and compile a pytorch object detector network. I generate object detection models with the [MMDetection](https://github.com/open-mmlab/mmdetection) framework, which is an open source object detection toolbox based on PyTorch. I noted that the Vitis [Model Zoo](https://github.com/Xilinx/Vitis-AI/tree/master/models/AI-Model-Zoo/model-list) includes object detector models for other frameworks as Caffe and Tensorflow. However, I have not found an example of a detector network for PyTorch, which is what I would like to do as my next step. So, I wonder wether pytorch detectors are fully supported by Vitis-AI.

¿Do you know if there are any issues related to pytorch detectors on Vitis? ¿And, do you know if there are a specific tutorial or example of a pytorch detector on Vitis?

Thanks.

**Comment by Premduth** [comment]
Please try this in

https://github.com/Xilinx/Vitis-AI-Tutorials

All ML tutorials moved there
