### ISSUE TITLE
Path to platforms

### ISSUE THREAD

**Issue by m-kru** [Xilinx/Vitis-Tutorials#55]
In the introduction it is written:

> To specify the location of the target development platform for Alveo U50 accelerator card, set the following environment variable:
> 
> `export PLATFORM_REPO_PATHS=<path to platforms>`

What is the default path to platforms after default installation?
I wanted to create new Application Project, but there are no platforms to choose from:
![image](https://user-images.githubusercontent.com/26227737/111833501-8e8cfe00-88f2-11eb-9496-1c1262b17ebb.png)

**Comment by imrickysu** [comment]
Default install path for Alveo platforms is /opt/xilinx/platforms
For embedded platforms, it can be extracted to any paths, including the path above. This path will be scanned by Vitis. If your platform is in this path, you won't need the PLATFORM_REPO_Paths environment variable.

**Comment by m-kru** [comment]
@imrickysu I have installed the platform files for U50 to `/opt/xilinx/platforms/`. Now, I can choose this platform in `Xilinx Vitis` program, however I am not able to choose this board in the `Vitis HLS` program.

![image](https://user-images.githubusercontent.com/26227737/117630912-f8e84f00-b17b-11eb-9825-265479322fae.png)

**Comment by imrickysu** [comment]
Hi @m-kru , Vitis HLS board setup shares the Vivado board setup. Vitis HLS only needs device part info from the board setup. The contents in Alveo platform is not needed by Vitis HLS.
Please launch Vivado and go to Tools -> Vivado Store to download the boards
