### ISSUE TITLE
Custom on board *.prototxt file for custom yolov4 model

### ISSUE THREAD

**Issue by hoadv-qh** [Xilinx/Vitis-Tutorials#58]
Hi,

I'm trying to running my custom yolov4 model on Ultra96v2, but output boxes is not correct.
I could convert/quantize/compile my custom yolov4 model with Vitisi AI docker ver1.3.411.

After compiling, I got a *.xmodel. I based on below example to create my application on Ultra96v2 target.
* /usr/share/vitis_ai_library/samples/yolov4
* This is from vitis ai runtime 1.3

I reused yolov4_leaky_spp_m.prototxt (from Model Zoo) and modified for my custom yolov4 model to run on board.
My modification is as below.
```
model {
  kernel {
     mean: 0.0            <-- (1) 3 times, with same value
     scale: 0.00390625    <-- (2) 3 times, with same value
     <snip>
  }
  model_type : YOLOv3
  yolo_v3_param {
    num_classes: 80        <-- (3) change from 80 to 2
    anchorCnt: 3             <-- (4) I don't know, so keep as it is
    layer_name: "160"     <-- (5) 133
    layer_name: "149"     <--     144
    layer_name: "138"     <--     155
    conf_threshold: 0.3
    nms_threshold: 0.45
    biases: 12            <-- (6) I don't know, so keep as it is
    <snip>
    test_mAP: false
  }
}
```

When I run **test_jpeg_yolov4**, nothing is outputed. I checked result image, but no box.
Then I reduced **conf_threshold** to very small 0.001. There are thousand of boxes in result image, but what I want is just 1 box.
Because test image only contains 1 object.
I increase **conf_threshold**, but i realized that the max **conf_threshold** when running is 0.00245.
I'm quite confused what is wrong here. Because my float model work well on host PC.

Could you help how to create correct *.prototxt for running on board when user has custom yolov model?
* For above point (3), (4), (5), and (6), how to decide those values?
* For above point (5) and (6), how to decide order values? (since they are same field name)

Thank you very much!

**Comment by Premduth** [comment]
Please try this in

https://github.com/Xilinx/Vitis-AI-Tutorials

All ML tutorials moved there
