### ISSUE TITLE
.dtsi file for ultra96 v2

### ISSUE THREAD

**Issue by JianmingTONG** [Xilinx/Vitis-Tutorials#62]
Hi,

I have a question regarding the Vitis_Platform_Creation:
```
https://github.com/Xilinx/Vitis-Tutorials/blob/master/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step2.md
```
What should I fill for the .dtsi file of ultra96 v2.

**Comment by imrickysu** [comment]
For the reference [dtsi ](https://github.com/Xilinx/Vitis-Tutorials/blob/master/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/ref_files/step2_petalinux/system-user.dtsi)provided in the sample code, 

- bootargs, zocl and axi_intc_0 nodes can be kept same.
- sdhci1 is not needed.
- Other Ultra96 specific device tree changes need to refer to Ultra96 doc.

**Comment by Premduth** [comment]
Closing under assumption it is resolved
