### ISSUE TITLE
AIE/D/01-lenet: makefile and readme needs modification

### ISSUE THREAD

**Issue by vivianyin** [Xilinx/Vitis-Tutorials#65]
https://github.com/Xilinx/Vitis-Tutorials/blob/master/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial/Makefiles/Makefile

Line 63, SYSROOT_PATH needs to be changed with the path to xilinx-versal-common-v2020.2 at user's end. This should be added to Readme.

Line 247, --package.sd_dir $(PLATFORM_REPO_PATHS)/sw/versal/xrt
This line should be removed?

Line 248-249, the paths need to be changed with the path to xilinx-versal-common-v2020.2 at user's end. This should be added to Readme.

**Comment by Premduth** [comment]
@ThomasXilinx  can you have someone look at this?

**Comment by imrickysu** [comment]
Hi @SURUTHI1605 , I think this lenet issue has been solved. Please confirm.

**Comment by SURUTHI1605** [comment]
I'm unable to access this link https://github.com/Xilinx/Vitis-Tutorials/blob/master/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial/Makefiles/Makefile

**Comment by imrickysu** [comment]
In 2022.2 branch, the makefile path is now https://github.com/Xilinx/Vitis-Tutorials/blob/2022.2/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial/Makefile .

Please fix in the latest branch.

Please document the environment variables need to be set before running the makefile, e.g. `$COMMON_IMAGE_VERSAL` on top of the Makefile and README, and provide proper error messages if these variables are not set.

**Comment by SURUTHI1605** [comment]
The environment variables need to be set was separately defined in sample_env_setup.sh script and the steps to reproduce the script was documented in README.
