### ISSUE TITLE
GS/Vitis/ZCU102: makefile needs modification

### ISSUE THREAD

**Issue by yka2ki** [Xilinx/Vitis-Tutorials#68]
https://github.com/Xilinx/Vitis-Tutorials/blob/master/Getting_Started/Vitis/example/zcu102/hw/Makefile

(**Original**)
package/sd_card.img: app.exe vadd.xclbin xrt.ini run_app.sh
    $(call ndef,ROOTFS)
    v++ -p -t ${TARGET} --config ../../src/zcu102.cfg ./vadd.xclbin **-o vadd.xclbin** \
        --package.out_dir package \
        --package.rootfs ${ROOTFS}/rootfs.ext4 \
        --package.sd_file vadd.xclbin \
        --package.sd_file ${ROOTFS}/Image \
        --package.sd_file xrt.ini \
        --**package.sd_file emconfig.json** \
        --package.sd_file app.exe \
        --package.sd_file run_app.sh

(**Modified**)
package/sd_card.img: app.exe vadd.xclbin xrt.ini run_app.sh
    $(call ndef,ROOTFS)
    v++ -p -t ${TARGET} --config ../../src/zcu102.cfg ./vadd.xclbin \
        --package.out_dir package \
        --package.rootfs ${ROOTFS}/rootfs.ext4 \
        --package.sd_file vadd.xclbin \
        --package.sd_file ${ROOTFS}/Image \
        --package.sd_file xrt.ini \
        --package.sd_file app.exe \
        --package.sd_file run_app.sh

**Comment by Premduth** [comment]
@imrickysu  please look at this

**Comment by imrickysu** [comment]
In Vitis 2021.1, the original Makefile generates error `ERROR: [v++ 60-2504] The input file and output file cannot be the same`. The Modified code can pass compilation, but it generates two xclbin files in sd_card directory: a.xclbin and vadd.xclbin.

Investigating how to reduce the redundancy.

**Comment by Candice-Yin** [comment]
> https://github.com/Xilinx/Vitis-Tutorials/blob/master/Getting_Started/Vitis/example/zcu102/hw/Makefile
> 
> (**Original**) package/sd_card.img: app.exe vadd.xclbin xrt.ini run_app.sh $(call ndef,ROOTFS) v++ -p -t ${TARGET} --config ../../src/zcu102.cfg ./vadd.xclbin **-o vadd.xclbin** --package.out_dir package --package.rootfs ${ROOTFS}/rootfs.ext4 --package.sd_file vadd.xclbin --package.sd_file ${ROOTFS}/Image --package.sd_file xrt.ini --**package.sd_file emconfig.json** --package.sd_file app.exe --package.sd_file run_app.sh
> 
> (**Modified**) package/sd_card.img: app.exe vadd.xclbin xrt.ini run_app.sh $(call ndef,ROOTFS) v++ -p -t ${TARGET} --config ../../src/zcu102.cfg ./vadd.xclbin --package.out_dir package --package.rootfs ${ROOTFS}/rootfs.ext4 --package.sd_file vadd.xclbin --package.sd_file ${ROOTFS}/Image --package.sd_file xrt.ini --package.sd_file app.exe --package.sd_file run_app.sh

Hi, I met the same problem, and then I modified it in your way. And I have another question, do you have any ideas? Thank you.

**Comment by Candice-Yin** [comment]
@imrickysu 
Hi, I met the same question, and I modified it in this way. But then I have another question, do you have any ideas? Thank you.
![image](https://user-images.githubusercontent.com/71826731/148390564-9c0ab78d-e62e-4499-829d-665cb7b8115f.png)

**Comment by imrickysu** [comment]
Hi @Candice-Yin , in your modified makefile, `package.out_dir` is being treated as a makefile target. Maybe you added an extra new line. Please check.

**Comment by Candice-Yin** [comment]
I solved it. Thank you very much! @imrickysu 
During hardware emulation, I have an error about `./package/launch_hw_emu.sh`. Could you please have a look at it?
![6c3848699a9bb3637843105213f4893](https://user-images.githubusercontent.com/71826731/148504995-6c1a3b76-af91-4751-8775-0355317cdd21.png)

**Comment by imrickysu** [comment]
Hi @Candice-Yin , I don't see a hard stop error in your messages.  Your Linux has boot up. There are some application level errors. Your Linux system should still work. If you hit enter, it should show you the input cursor.

**Comment by Candice-Yin** [comment]
hi @imrickysu , it displayed “ Current directory: 0" when I continued typing.
![3c6a82ce12df8b5931bcb27bf076693](https://user-images.githubusercontent.com/71826731/148506282-c8e702d4-ca00-4044-bd65-3885903e8983.png)

**Comment by imrickysu** [comment]
@Candice-Yin  It's a valid error message. Please add your xclbin file as an argument to app.exe.

**Comment by Candice-Yin** [comment]
@imrickysu You helped me a lot, thx!

**Comment by AnusheelXilinx** [comment]
Closing the thread as there are no open concerns.

Thanks
Anusheel
