### ISSUE TITLE
How can I get vadd.cpp file?

### ISSUE THREAD

**Issue by kaoriuky** [Xilinx/Vitis-Tutorials#7]
Hi, I'm just tried Vitis-Tutorials for 
getting-started-rtl-kernels.
And Finally I get the xml from VITIS IDE and make XO files, however,
final step, build the Project section. I meet a problem.
my  Vitis  IDE Problems console makes 2 warnings as follow.
  1. No binary containers were found.
   2. No host source files were found.

Actually, to create binary container, I cannot understand select icon. cause of no popup from IDE, also no action from IDE. So I did change project configuration setting  2->1. Emulation-HW. and Click Run Configuration on VITIS IDE, but in my case. Arguments tap is empty when i click Arguments tap. It is different status git hub instruction. (it have to be exists u200~ arguments by RTL kernel tutorials,)

So. where can i get vadd.cpp file from you already described on your github tutorials in first page.
or,
If I have to use host.cpp file instead of vadd.cpp file. (supposed your mistake)
How can I make binary container to delete warning.
And how can I add defult setting Argumnts tap as this tutorials?
I hope to check this guide error or my mistake.

**Comment by Ssicayoon** [comment]
Hi, kaoriuky
You can try the beginner tutorial [develop accelerated applications using the Vitis™ core development kit](https://github.com/Xilinx/Vitis-Tutorials/tree/master/docs/vitis-getting-started) to start your trip.
_**Getting-started-rtl-kernels**_ is an intermediate tutorial.

In addition, you need to _**git clone**_ the repository [Vitis-Tutorials](https://github.com/Xilinx/Vitis-Tutorials.git) to your local. All the reference files, including vadd.cpp, are included in [Vitis-Tutorials](https://github.com/Xilinx/Vitis-Tutorials.git).
