### ISSUE TITLE
question about val/train images for yolov4 tutorial

### ISSUE THREAD

**Issue by arrow53** [Xilinx/Vitis-Tutorials#75]
For the tensorflow workflow there are scripts to generate val/train images. From the scripts it looks as though the images and labels should go in the same location. Is this correct?

https://github.com/Xilinx/Vitis-Tutorials/blob/master/Machine_Learning/Design_Tutorials/07-yolov4-tutorial/scripts/gen_yolo_val_labels.sh

If it is, then I'm not sure why this section of the annotation creation script is removing that directory

https://github.com/Xilinx/Vitis-Tutorials/blob/master/Machine_Learning/Design_Tutorials/07-yolov4-tutorial/scripts/gen_coco_annotations.py#L72

Could you clarify?

Should I use different directories and then move the txt files over after they are created?

**Comment by Premduth** [comment]
Please try this in

https://github.com/Xilinx/Vitis-AI-Tutorials

All ML tutorials moved there
