### ISSUE TITLE
Yolov4 using VOC Data Set and converting to Caffe Tutorial

### ISSUE THREAD

**Issue by Liu-guoxin** [Xilinx/Vitis-Tutorials#80]
set number of classes to 20 for each output layer
set filter size of convolutional layer before each output layers to 75

how to  set classes  and filter.

I cant run  bash scripts/run_vai_c_zu104.sh success .

**Comment by Premduth** [comment]
Please try this in

https://github.com/Xilinx/Vitis-AI-Tutorials

All ML tutorials moved there
