### ISSUE TITLE
Python code for the Post Processing Image of Keras FCN8 UNET segmentation

### ISSUE THREAD

**Issue by majlucaaa** [Xilinx/Vitis-Tutorials#81]
Hello, I am working with Python and so far following the [app_mt.py](https://github.com/Xilinx/Vitis-Tutorials/blob/master/Machine_Learning/Design_Tutorials/05-Keras_FCN8_UNET_segmentation/files/target_zcu102/code/src/app_mt.py) code, but realized that there is no code to see the post processed image (how the final Segmented Image looks like). There is the code for this in [main_mt.cc](https://github.com/Xilinx/Vitis-Tutorials/blob/master/Machine_Learning/Design_Tutorials/05-Keras_FCN8_UNET_segmentation/files/target_zcu102/code/src/main_mt.cc) but I am having problems to pass it to Python. Can I see somewhere the code for this? Or can someone help me?

**Comment by Premduth** [comment]
Please try this in 

https://github.com/Xilinx/Vitis-AI-Tutorials

All ML tutorials moved there
