### ISSUE TITLE
Missing .prototxt file after compilation and my md5sum.txt file doesn‘t have .prototxt

### ISSUE THREAD

**Issue by littlemww** [Xilinx/Vitis-Tutorials#86]
I'm trying to run test_accuracy_yolov3_voc on the ZCU104 but it aborts because of a missing .prototxt file.

 ./test_accuracy_yolov3_voc 2007_test_gt.txt yolov4_person_pred.txt

[libprotobuf ERROR google/protobuf/text_format.cc:324] Error parsing text-format vitis.ai.proto.DpuModelParamList: 1:5: Message type "vitis.ai.proto.DpuModelParamList" has no field named "name".

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0610 13:48:07.609874  1187 configurable_dpu_task_imp.cpp:140] Check failed: ok cannot parse config file. config_file=/usr/share/vitis_ai_library/models/yolov4_person/yolov4_person.prototxt
*** Check failure stack trace: ***

But I have copy the original yolov4_person.prototxt (Generated when I run the script ：bash scripts/darknet_convert.sh )to the board. 
![image](https://user-images.githubusercontent.com/82634086/124351054-c3675b80-dc2a-11eb-8de3-49e5bb695b32.png)

when I open the md5sum.txt file generated at compile time(I compiled according to the yolov4 tutorial, and there were no errors when compiling) I found that there was only one line inside：
![image](https://user-images.githubusercontent.com/82634086/124350908-ef361180-dc29-11eb-90f1-cd4b3e649b7a.png)
but I see other md5sum.txt in the model are as follows:
![image](https://user-images.githubusercontent.com/82634086/124350970-463be680-dc2a-11eb-8532-569763e7aadb.png)

So Is it because of the lack of information of prototxt in this file？If so, how to generate the correct md5sum.txt file at compile time？

Thanks in advance

**Comment by Premduth** [comment]
@allyzhou should this be moved to the Vitis-AI repo?

**Comment by allyzhou** [comment]
> @allyzhou should this be moved to the Vitis-AI repo?

Yes, this should be transferred to https://github.com/Xilinx/Vitis-AI-Tutorials, @ryanvergel can you help transfer issue to that repo. Thanks.

**Comment by Premduth** [comment]
@littlemww Can you look at the new repo: https://github.com/Xilinx/Vitis-AI-Tutorials and if it is still there, open the issue there? I am going to close this issue in this repo for now..
