### ISSUE TITLE
unable to run hw_emu

### ISSUE THREAD

**Issue by dharawolvpatel** [Xilinx/Vitis-Tutorials#9]
Building these tutorials works fine when using sw_emu. But I'm unable to build these applications using hw_emu. I always get the following errors: 
![image](https://user-images.githubusercontent.com/54337299/83089731-e6006b80-a04b-11ea-977a-6faa64e0f1e2.png)

**Comment by Ssicayoon** [comment]
I note that your run directory is not `makefile`.
[Run Hardware Emulation](https://github.com/Xilinx/Vitis-Tutorials/blob/master/docs/bloom/baseline_fpga.md#run-hardware-emulation) gives the command to run hw_emu.
Try it and see whether it works.

**Comment by dharawolvpatel** [comment]
the directory I'm running "make" is the following: 
/home/dharap/xilinx/Vitis-Tutorials/Vitis-Tutorials/docs/bloom/design/makefile

**Comment by Ssicayoon** [comment]
@dharawolvpatel 
Have you installed the platform `xilinx_u200_xdma_201830_2` after your installation of Vitis?

**Comment by dharawolvpatel** [comment]
yes, its there! sw_emu works fine with it.

**Comment by Ssicayoon** [comment]
@dharawolvpatel 
I have tried the `bloom` tutorial and no error occurs.
Notice that for [Kernel Code Modifications](https://github.com/Ssicayoon/Vitis-Tutorials/blob/master/docs/bloom/baseline_fpga.md#kernel-code-modifications), I copy `computer_score_fpga.cpp` and `compute_score_host.cpp` in `/design/refernce_files/baseline_fpga` to `/design/src/baseline_fpga`.
Have a try.

**Comment by ryanvergel** [comment]
Thank you for your input. I will create an internal ticket so that the Author can review this issue.
